export const developerKo = { responsePerformance: {
  range: { h1: "최근 1시간", h6: "최근 6시간", h24: "최근 24시간", d7: "최근 7일" }, status: { all: "전체 상태", success: "성공", failed: "실패" },
  duration: { ms: "{value, number}ms", seconds: "{value, number}초", minutesSeconds: "{minutes, number}분 {seconds, number}초" },
  operation: { inventory_workspace_read: "재고 작업공간 조회", inventory_quantity_ledger_read: "재고 수량 원장 조회", inventory_quantity_ledger_movements_read: "재고 수불 이력 조회", inventory_inbound_reconciliation_read: "입고 대조 상세 조회", inventory_device_create: "재고 추가", inventory_device_update: "기존 재고 수정", inventory_device_delete: "재고 삭제", inventory_bulk_correction: "재고 일괄 수정", inventory_audit_save: "재고실사 저장", inspection_record_save: "검수 기록 저장", inbound_batch_read: "입고 차수 조회", inbound_batch_create: "입고 차수 생성", inbound_batch_update: "입고 차수 수정", inbound_batch_delete: "입고 차수 삭제", inbound_purchase_confirm: "매입 확정", inbound_purchase_price_save: "매입가 저장", shipment_orders_read: "출고 주문 조회", shipment_delivering_read: "배송 중 목록 조회", shipment_print_history_read: "출고 출력 이력 조회", shipment_inventory_candidates_read: "출고 재고 후보 조회", shipment_address_change_read: "배송지 변경 건 조회", shipment_packing_check: "포장 검증", shipment_print_batch_create: "출고 목록 생성", shipment_print_batch_update: "출고 목록 상태 변경", return_action: "반품 처리", return_list_read: "반품 목록 조회", statistics_dashboard_read: "통계 대시보드 조회", statistics_sales_read: "매출 통계 조회", sales_channel_sync_check_read: "판매 채널 동기화 점검 조회", sales_channel_sync_check_recheck_inventory: "판매 채널 재고 다시 점검", sales_channel_sync_check_repair_inventory: "판매 채널 재고수량 복구", sales_channel_write_review_action: "판매 채널 쓰기 점검 처리" },
  span: { empty: "기록된 세부 구간이 없습니다.", count: "{count, number}회", note: "상위 구간과 내부 구간이 함께 기록될 수 있어 span 시간의 합은 전체 시간과 일치하지 않을 수 있습니다." },
  columns: { operation: "조작", samples: "표본", sampleResult: "성공 {success, number} / 실패 {failed, number}", average: "평균", max: "최장", queryAverage: "누적 DB 평균", txAverage: "TX 진입 평균", clientSamples: "Client 표본", clientCoverage: "{count, number}건 / {coverage, number}%", clientAverage: "Client 평균", outsideAverage: "서버 밖 평균", startedAt: "시작 일시", status: "상태", total: "전체", query: "누적 DB", tx: "TX 진입", clientTotal: "Client 전체", outside: "서버 밖", target: "대상", count: "{count, number}건" },
  summary: { measured: "측정 표본", success: "성공 표본", failed: "실패 표본", slow: "1초 이상", p50: "표본 P50", p95: "표본 P95", max: "최장" },
  notice: { production: "운영 환경에서는 빠른 성공 요청이 표본 수집됩니다. 표시된 건수와 분포는 전체 트래픽 통계가 아닙니다.", truncated: "조건에 맞는 {matched, number}건 중 최근 {analyzed, number}개 표본을 기준으로 집계했습니다.", ingestion: "성능 로그 적재 상태: 대기 {pending, number}건 / 유실 {dropped, number}건{failure}" },
  filter: { range: "성능 조회 기간", status: "성능 요청 상태", operation: "성능 조작 종류", allOperations: "전체 조작", search: "성능 trace 검색", searchPlaceholder: "조작, API 경로, Trace ID, 오류 검색", refresh: "새로고침" },
  operationPanel: { title: "조작별 서버 처리 성능", subtitle: "성공 표본의 지연 시간과 trace 안에서 측정된 누적 DB 구간을 비교합니다.", count: "{count, number}개 조작", loading: "성능 표본을 불러오는 중입니다.", empty: "측정된 조작이 없습니다." },
  tracePanel: { title: "요청 trace", subtitle: "서버가 기록한 최근 요청 표본입니다.", count: "{count, number}건", loading: "성능 trace를 불러오는 중입니다.", empty: "조건에 맞는 trace가 없습니다." },
  detail: { title: "Trace 상세", subtitle: "전체 시간, DB, 트랜잭션과 세부 측정 구간을 확인합니다.", loading: "상세 정보를 불러오는 중입니다.", select: "왼쪽 표에서 trace를 선택하세요.", operation: "조작", copyTrace: "Trace ID 복사", started: "시작", total: "전체 시간", actor: "실행자", status: "상태", clientGateway: "Client / Gateway", clientGatewayTime: "Client gateway", responseHeader: "응답 헤더 수신", responseComplete: "응답 소비 완료", body: "본문 처리", outside: "서버 밖 구간", outsideNote: "서버 밖 구간은 Client 응답 소비 완료에서 중앙 서버 trace 시간을 뺀 값입니다. 클라이언트 표본이 없으면 0이 아니라 -로 표시합니다.", dbTx: "DB / 트랜잭션", query: "쿼리", totalQuery: "누적 DB query", longestQuery: "최장 쿼리", transaction: "트랜잭션", txCallback: "TX 콜백 진입", txExecution: "TX 실행", dbNote: "병렬 query는 각각의 시간을 합산하므로 누적 DB 시간이 전체 응답보다 클 수 있습니다. TX 콜백 진입은 DB 잠금 대기 시간과 동일하지 않습니다.", spans: "세부 구간", environment: "실행 환경", errorCode: "오류 코드", error: "오류" },
  error: { report: "응답 성능 기록을 불러오지 못했습니다.", detail: "성능 trace 상세를 불러오지 못했습니다." },
  system: "시스템",
}, tools: {
  common: { check: "확인", loading: "조회 중입니다.", yes: "예", no: "아니오", allowed: "허용", blocked: "차단", developer: "개발자", normal: "정상", warning: "확인 필요", exists: "존재", missing: "없음", invalidJson: "응답을 JSON으로 읽지 못했습니다. ({status, number})", requestFailed: "API 요청에 실패했습니다. ({status, number})" },
  roles: { viewer: "조회전용", staff: "사원급", manager: "중간관리자급", leader: "리더급" },
  diagnostics: { user: "로그인 사용자", environment: "실행 환경", production: "운영", development: "개발", node: "Node 런타임", connected: "연결", workerSummary: "등록 {registered, number} / DB {persisted, number} / 실행 {running, number}", hasErrors: "오류 있음", menuAccess: "메뉴 접근", devices: "기기 데이터", workerFailures: "worker 실패", otpKey: "OTP 키", title: "현재 런타임 상태", checkedAt: "최종 조회: {date}", description: "서버 진단 API를 호출합니다.", refresh: "진단 새로고침", tableCounts: "주요 테이블 카운트", workerErrors: "worker 오류" },
  sandbox: { form: "개발자 API 샌드박스 요청", title: "요청 작성", description: "내부 API만 호출할 수 있고, 보호 API와 재귀 호출은 서버에서 차단합니다.", writeAllowed: "쓰기 허용", readFirst: "읽기 우선", run: "요청 실행", allowWrite: "POST/PATCH/DELETE 같은 쓰기 요청 실행을 허용합니다.", requestJson: "요청 JSON", response: "응답", responsePlaceholder: "응답 결과가 여기에 표시됩니다.", rules: "샌드박스 보호 규칙", internalOnly: "/api 내부 경로만 허용", internalOnlyDescription: "외부 URL 호출과 SSRF 위험을 차단합니다.", authBlocked: "인증/OTP API 차단", authBlockedDescription: "로그인, 로그아웃, OTP 등록/검증 API는 직접 호출할 수 없습니다.", writeConfirm: "쓰기 요청 확인", writeConfirmDescription: "쓰기 method는 체크박스를 켜야 서버가 실행합니다." },
  adb: { api: "ADB API", apiReady: "응답", apiWaiting: "대기", connected: "연결 기기", unavailable: "오프라인/미승인", emulator: "에뮬레이터", title: "ADB 기기 조회", description: "현재 실행 환경에서 ADB 연결 기기를 조회합니다.", refresh: "ADB 새로고침", serial: "ADB Serial", status: "상태", model: "모델코드", carrier: "통신사", storage: "용량", firstCall: "최초 통화일", camera: "카메라", warning: "경고", warningText: { carrierReview: "통신사 확인 필요", accountReview: "계정 확인 필요", accountQueryFailed: "계정 조회 실패", offline: "ADB 상태: offline\nUSB 연결을 다시 꽂거나 ADB 서버를 재시작하세요.", unauthorized: "ADB 상태: unauthorized\n휴대폰에서 USB 디버깅 허용을 승인하세요.", unknown: "ADB 상태: {state}", queryFailed: "ADB 조회 실패:\n{detail}" }, empty: "표시할 ADB 기기가 없습니다." },
  database: { title: "DB 상태", checkedAt: "최종 조회: {date}", description: "PostgreSQL과 Prisma 기준 상태를 조회합니다.", refresh: "상태 조회", file: "DB 파일", integrity: "PostgreSQL 제약 무결성", applied: "{count, number}건 적용", tableMissing: "테이블 없음", queried: "조회", caution: "주의", migrations: "마이그레이션 파일", noSql: "SQL 없음", noMigrations: "마이그레이션 파일이 없거나 아직 조회되지 않았습니다.", tables: "주요 테이블" }
} } as const;
export type DeveloperMessages = typeof developerKo;
