export const statisticsKo = {
  visual: { empty: "집계할 데이터가 없습니다.", lineAria: "{title} 선 그래프", lineWithGapsAria: "{title}. 결측 구간은 선을 연결하지 않습니다." },
  periodToolbar: { aria: "통계 조회 기간", title: "통계 조회 기간", default: "기본 90일", custom: "직접 지정", applied: "적용 중: {from} ~ {to} · 한국 시간 기준 어제까지", from: "시작일", to: "종료일", apply: "기간 적용", reset: "기본 90일로 되돌리기", error: { incomplete: "통계 시작일과 종료일을 함께 입력해야 합니다.", invalidDate: "통계 기간은 YYYY-MM-DD 형식의 올바른 날짜여야 합니다.", reversed: "통계 시작일은 종료일보다 늦을 수 없습니다.", openDate: "통계 종료일은 한국 시간 기준 어제까지만 지정할 수 있습니다.", unknown: "통계 기간을 확인하지 못했습니다." } },
  calculationScope: { method: { liveFallback: "실시간 대체 계산", live: "실시간 계산", snapshot: "저장된 일별 통계", automaticFallback: "저장 통계 자동 대체", customPeriod: "직접 지정 기간", delayed: "기본 기준보다 {days, number}일 지연", current: "기본 90일 · 최신 저장본", defaultPeriod: "기본 90일", custom: "직접 지정" }, fallback: { notFound: "저장 통계가 아직 없어 현재 원장을 실시간으로 계산했습니다.", tooOld: "저장 통계가 2일 이상 오래되어 현재 원장을 실시간으로 계산했습니다.", invalid: "저장 통계를 안전하게 확인할 수 없어 현재 원장을 실시간으로 계산했습니다." }, delayed: "저장 통계가 현재 기본 기준보다 {days, number}일 이전입니다. 실제 데이터 마감은 {date}입니다.", labels: { method: "계산 방식", period: "집계 기간", comparison: "비교 기간", cutoff: "데이터 마감" }, days: "{days, number}일", comparisonDays: "{days, number}일 · 동일 길이", cutoffDelayed: "현재 기본 기준보다 이전", cutoffCurrent: "한국 시간 기준 어제까지" },
  metric: { count: "{count, number}건", unit: "건", sample: "표본 {count, number}건", ratio: "{numerator, number} / {denominator, number}건", priceCoverage: "가격 확인 {priced, number} / {total, number}건", priceCoveragePercent: "가격 확인 {priced, number} / {total, number}건 · {coverage, number}%", noSample: "표본 없음", noSampleAnomaly: "표본 없음 · 이상치 {count, number}건 제외", p90: "P90 {hours, number}시간", p90Unavailable: "P90 -", anomaly: " · 이상치 {count, number}건 제외", hours: "{hours, number}시간", month: "{year, number}년 {month, number}월", unavailableReason: { NO_DENOMINATOR: "집계 가능한 분모가 없습니다.", NO_MATURE_SALES: "아직 성숙한 판매가 없습니다.", NO_CONFIRMED_RETURN_FAULT_SAMPLE: "귀책이 확인된 반품 접수가 없습니다.", NO_CONFIRMED_RETURN_INSPECTION_SAMPLE: "확정된 반품 검수 표본이 없습니다.", NO_CURRENT_MATURE_COHORT: "현재 성숙 cohort 판매가 없습니다.", NO_PREVIOUS_MATURE_COHORT: "직전 성숙 cohort 판매가 없습니다.", NO_CURRENT_30_DAY_MATURE_COHORT: "아직 완전히 성숙한 최근 30일 판매 cohort가 없습니다.", NO_PREVIOUS_30_DAY_MATURE_COHORT: "비교할 직전 성숙 30일 판매 cohort가 없습니다.", NO_RETURN_RECEIPTS: "조회 조건에 해당하는 고객 반품 접수가 없습니다.", NO_MATURE_PURCHASE_BATCHES: "{days, number}일 관찰이 끝난 매입 회차가 없습니다.", NO_LINKED_INBOUND_INSPECTION_SAMPLE: "연결된 입고 검수 표본이 없습니다.", NO_TERMINAL_INBOUND_BATCHES: "종결된 입고 회차가 없습니다.", NO_ORIGINAL_SUPPLIER_SALES_SAMPLE: "판매 당시 원매입처가 기록된 판매 표본이 없습니다.", INVENTORY_LEDGER_UNAVAILABLE: "기간 재고 원장을 복원할 수 없습니다.", NO_INVENTORY_OR_SALES: "선택 기간에 창고 재고와 판매가 없습니다.", SALES_WITHOUT_INVENTORY_DENOMINATOR: "판매 완료는 있지만 창고 보유 재고 분모가 0입니다.", SALE_LEDGER_TIMESTAMP_UNVERIFIED: "판매 원장 시각을 검증할 수 없습니다." } },
  sales: {
    unknown: { sku: "미기록 SKU", model: "미기록 기종", storage: "미기록 용량", color: "미기록 색상", grade: "미기록 등급", warranty: "미기록 보증", channel: "미기록 채널" },
    priceBand: { PRICE_LT_100K: "10만원 미만", PRICE_100K_199K: "10~20만원", PRICE_200K_299K: "20~30만원", PRICE_300K_399K: "30~40만원", PRICE_400K_499K: "40~50만원", PRICE_500K_599K: "50~60만원", PRICE_600K_PLUS: "60만원 이상", PRICE_UNKNOWN: "가격 미확인" },
    count: "{count, number}건",
    dimension: { model: "기종", storage: "용량", color: "색상", grade: "판매 등급", warranty: "보증 그룹", channel: "판매 채널" },
    coverage: { title: "집계 원천과 신뢰도", subtitle: "판매 통계를 해석하기 전에 원장 상태와 가격·원가·소요기간의 확인 범위를 확인하세요.", ledger: "조회 원장", ledgerDescription: "전체 원장 {count, number}건", status: "판매 상태", statusValue: "판매 유지 {count, number}건", statusDescription: "반품 후 원판매 {count, number}건 포함", salesPrice: "판매가 확인 범위", purchasePrice: "매입가 확인 범위", profit: "매출총이익 비교 범위", ratio: "{available, number} / {total, number}건", leadSample: "판매 소요기간 표본", leadDescription: "미기록 {missing, number} · 이상 {invalid, number}건", soldAtExcluded: "판매 시각 제외", soldAtDescription: "형식 오류 {invalid, number} · 미래 {future, number}건", generatedAt: "생성 시각", periodAll: "선택 기간 전체", warning: "통계에서 확인이 필요한 데이터가 있습니다.", success: "조회 범위에서 별도로 확인할 누락·시간 이상이 없습니다.", excludedStatus: "판매 종결 상태가 아닌 원장 {count, number}건 제외", invalidSoldAt: "판매 시각을 해석할 수 없는 원장 {count, number}건 제외", futureSoldAt: "미래 판매 시각 원장 {count, number}건 제외", missingSalesPrice: "판매가 미기록 {count, number}건", missingPurchasePrice: "매입가 미기록 {count, number}건", missingPurchaseAt: "매입 확정 시각 미기록 {count, number}건", invalidLead: "판매 소요기간 이상 {count, number}건 제외" },
    presentation: { priceCoverage: "가격 확인 {priced, number} / {total, number}건", margin: "이익률 {value}%", marginUnavailable: "이익률 -", profitDetail: "{margin} · 비교 {comparable, number} / {total, number}건 · {coverage, number}%", anomaly: " · 이상 {count, number}건 제외", days: "{days, number}일", leadDetail: "표본 {sample, number} / {total, number}건 · {coverage, number}%{anomaly}" },
    summary: { sales: "확정 판매", salesDescription: "판매 원장 PG 기준", amount: "판매금액", averagePrice: "평균 판매가", purchaseCost: "매입 원가", grossProfit: "상품 매출총이익", leadTime: "평균 판매 소요" },
    monthly: { chart: "월별 확정 판매량", title: "월별 판매 성과", subtitle: "판매 원장의 원 판매일을 한국 표준시 월로 묶었습니다.", month: "월", sales: "판매", amount: "판매금액", average: "평균 판매가", grossProfit: "상품 매출총이익" },
    product: { title: "상품별 판매 성과", subtitle: "배송 완료 시점에 고정된 판매 원장 상품 속성별 비교입니다.", model: "기종", storage: "용량", color: "색상", grade: "등급", warranty: "보증", sales: "판매", share: "비중", amount: "판매금액", grossProfit: "상품 매출총이익", lead: "판매 소요", days90: "90일+" },
    composition: { title: "판매 구성", subtitle: "한 번에 하나의 상품 속성을 선택해 구성 비중과 금액을 비교합니다.", sales: "판매", share: "비중", amount: "판매금액", grossProfit: "상품 매출총이익" },
    priceGrade: { title: "가격대와 판매 등급", subtitle: "판매가 미기록 건은 가격 미확인 행에 남겨 커버리지 손실을 숨기지 않습니다.", priceBand: "가격대", total: "합계" },
    leadDistribution: { title: "판매 소요기간 구성", subtitle: "매입 확정일부터 원 판매일까지 계산할 수 있는 표본만 구간별로 비교합니다.", days0_29: "0~29일", days30_59: "30~59일", days60_89: "60~89일", days90Plus: "90일 이상" },
    channel: { title: "판매 채널 성과", subtitle: "채널별 판매 규모와 가격·원가가 모두 있는 상품의 매출총이익을 비교합니다.", channel: "채널", sales: "판매", share: "비중", amount: "판매금액", average: "평균 판매가", grossProfit: "상품 매출총이익", lead: "판매 소요" },
    loading: { initial: "판매 통계를 불러오는 중입니다.", aggregating: "판매 원장을 집계하고 있습니다.", error: "판매 통계를 불러오지 못했습니다.", retry: "다시 시도", refresh: "같은 조건으로 통계를 다시 확인하고 있습니다. 현재 결과는 계속 표시합니다." }
  },
  inventory: {
    unavailable: { aggregate: "집계 불가", confirm: "확인 불가" },
    unit: { count: "{count, number}건", row: "{count, number}행", device: "{count, number}대", days: "{count, number}일", turns: "{count, number}회" },
    period: { days30: "최근 30일", days90: "최근 90일", year1: "최근 1년", all: "전체 기간", custom: "직접 지정", range: "{from} ~ {to} · {days, number}일", sectionTitle: "{period} 재고 흐름과 판매 회전율" },
    status: { sellable: "판매 가능", allocated: "주문 배정", restricted: "판매 제한·점검", delivering: "배송 중", trackingException: "배송 추적 예외", finalDelivery: "판매 종결", claimUnknown: "고객 클레임 진행·위치 미확정", created: "신규 생성", removed: "재고 삭제", previous: "이전 상태" },
    age: { days0_29: "0~29일", days30_59: "30~59일", days60_89: "60~89일", days90Plus: "90일 이상" },
    integrity: { emptyPeriod: "선택 기간에 집계할 재고 흐름과 판매가 없습니다.", emptyInventory: "집계할 재고가 없습니다.", partial: "{area} 원장의 일부 정합성을 확인할 수 없어 영향을 받는 수치를 숨겼습니다.", asOf: "기준일 재고", aging: "재고 연령", period: "기간 재고 흐름" },
    metric: { noInventory: "대상 재고 없음", noAmount: "확인 금액 없음", costUnavailable: "매입원가 집계 불가", costDetail: "{priced} 확인 · {missing} 미확인 · {coverage} 확인", turnoverUnavailable: "회전율을 계산할 수 없습니다.", turnoverDetail: "판매 {sold} ÷ 일평균 재고 {average}" },
    asOf: { total: "{date} 기준 전체 재고", closing: "{date} 마감 기준", sellable: "판매 가능", allocated: "주문 배정", restricted: "판매 제한·점검", longTerm: "장기 재고", longTermDescription: "30일 이상 · 주문 배정 제외", longTermCost: "장기 재고 매입원가", composition: "{date} 기준 재고 상태 구성", compositionDescription: "선택한 마감일의 모든 재고를 판매·출고·배송·클레임 의미에 따라 한 번씩만 분류합니다.", group: "상태 그룹", included: "포함 상태", quantity: "수량", ratio: "비율" },
    aging: { title: "재고 연령과 장기 재고 부담", description: "{date} 마감 시점의 창고 보유 주기를 기준으로 하며 주문 배정 재고는 장기 재고에서 제외합니다.", pending: "원장 보유 주기를 확인한 뒤 재고 연령을 표시합니다.", sku: "SKU / 상품", grade: "등급", target: "기준일 대상", longTerm: "장기 재고", cost: "확인 매입원가", missingPrice: "가격 미확인", empty: "기준일에 장기 재고 대상 SKU가 없습니다." },
    flow: { turnover: "판매 회전율", sold: "판매 완료", averageInventory: "일평균 창고 재고", averageDescription: "KST 날짜별 마감 수량 평균", newInventory: "신규 재고 유입", newDescription: "최초 재고 생성", customerReturn: "고객 반품 재입고", customerReturnDescription: "판매 후 창고 재진입", otherReturn: "기타 재입고", otherReturnDescription: "고객 반품 외 재진입", exit: "창고 이탈", exitDescription: "배송·클레임 등 창고 외 이동", removed: "재고 삭제", removedDescription: "원장에서 제거된 수량", closingChart: "일별 창고 재고와 판매", closingChartDescription: "모든 날짜의 흐름은 유지하고 축 표시는 읽기 좋은 간격으로 줄입니다.", closing: "창고 마감 재고", movementChart: "일별 재고 유입·이탈", movementChartDescription: "신규 유입, 재입고와 창고 이탈·삭제를 같은 기간에서 비교합니다.", new: "신규 유입", transition: "재고 상태 이동", transitionDescription: "선택 기간에 발생한 상태 그룹 간 이동을 작업 단위로 집계합니다.", noTransition: "선택 기간에 재고 상태 이동이 없습니다.", skuTurnover: "SKU별 판매 회전율", skuTurnoverDescription: "판매 완료 수량과 일평균 창고 재고를 같은 SKU 기준으로 비교합니다.", sku: "SKU / 상품", average: "평균 재고", emptySku: "선택 기간에 SKU별 회전율을 표시할 데이터가 없습니다." },
    scope: { title: "집계 기준과 복원 범위", description: "조회 기간과 마감 기준, 기준일 재고를 복원할 때 제외하거나 확인하지 못한 근거를 함께 표시합니다.", asOf: "기준일 재고", asOfDescription: "재고 {inventory, number}건 · 원장 {ledger, number}대", cutoff: "마감 이후 제외", cutoffValue: "{count, number}행", cutoffDescription: "판매 {count, number}건 제외", price: "기준일 가격 근거", noneExcluded: "제외 없음", excluded: "{count, number}건 제외", reconstructionComplete: "재고 복원 검증 완료", reconstructionNeeded: "복원 확인 필요 {count, number}건" },
    loading: { aggregating: "재고 원장과 판매 원장을 집계하고 있습니다.", initial: "재고 통계를 불러오는 중입니다.", error: "재고 통계를 불러오지 못했습니다.", retry: "다시 시도", refresh: "같은 조건으로 통계를 다시 확인하고 있습니다. 현재 결과는 계속 표시합니다." }
  },
  purchase: {
    presentation: { observing: "관찰 중" },
    coverage: {
      title: "데이터 기준과 신뢰도", subtitle: "매입 통계를 해석하기 전에 가격·검수·판매 연결 범위를 확인하세요.", terminalInbound: "종결 입고 회차", terminalDescription: "확정 매입 {purchases, number} · 매입처 반품 {returns, number}", priceCoverage: "매입가 확인 범위", countRatio: "{available, number} / {total, number}건", supplierCoverage: "매입처 확인 범위", supplierDescription: "종결 회차 {total, number}건 중", inspectionLinkRate: "입고 검수 연결률", gradeCoverage: "매입 등급 확인", gradeDescription: "미확인 {missing, number}건", policyEvidence: "가격 정책 증거", policyDescription: "입력 방식 {modes, number} · 기준가 {references, number}건", salesLinkRate: "판매 원매입 연결률", salesLinkDescription: "원매입처 snapshot {percent, number}%", generatedAt: "생성 시각", periodAll: "선택 기간 전체", warning: "통계에서 확인이 필요한 데이터가 있습니다.", success: "조회 범위에서 별도로 확인할 누락·시간 이상이 없습니다.",
      missingPrice: "매입가가 기록되지 않은 확정 매입 {count, number}건", missingSupplier: "매입처가 기록되지 않은 종결 회차 {count, number}건", missingInspection: "입고 검수가 연결되지 않은 종결 회차 {count, number}건", missingGrade: "매입 등급을 확인할 수 없는 종결 회차 {count, number}건", missingPolicy: "가격 입력 방식을 확인할 수 없는 확정 매입 {count, number}건", missingInboundSale: "원매입 회차가 연결되지 않은 판매 {count, number}건", missingSupplierSnapshot: "판매 당시 원매입처가 기록되지 않은 판매 {count, number}건", invalidTimestamp: "날짜를 해석할 수 없는 기록 {count, number}건", negativeDuration: "시간 순서 이상으로 기간 계산에서 제외한 기록 {count, number}건"
    },
    summary: { purchaseCount: "확정 매입 회차", purchaseBasis: "매입 확정 기준", amount: "매입금액", averagePrice: "평균 매입가", priceConfirmed: "가격 확인 {count, number}건", suppliers: "매입처", supplierDescription: "종결 회차의 고유 매입처", supplierReturnRate: "매입처 반품률" },
    monthly: { title: "월별 매입 결과 추이", subtitle: "확정 매입은 매입 확정일, 매입처 반품은 최초 반품 전환일 기준입니다.", purchase: "확정 매입", supplierReturn: "매입처 반품", inspectionDefect: "검수 불량 결과", amountTitle: "월별 매입 금액", amountSubtitle: "가격 미입력 건을 0원으로 포함하지 않습니다.", month: "월", count: "매입", amount: "매입액", priceConfirmed: "가격 확인", priceMissing: "가격 미입력", defect: "검수 불량" },
    product: { title: "상품별 매입 cohort 성과", subtitle: "기종·용량·매입등급별 확정 매입과 성숙 cohort의 판매 전환을 비교합니다.", model: "기종", storage: "용량", grade: "매입등급", purchase: "확정 매입", amount: "매입액", average: "평균가", supplierReturnRate: "매입처 반품률", defectRate: "검수 불량률", conversion30: "30일 판매전환", conversion60: "60일 판매전환", conversion90: "90일 판매전환" },
    supplier: { title: "매입처 성과", subtitle: "매입처 반품과 판매 후 고객 반품 확정을 서로 다른 결과로 비교합니다.", supplier: "매입처", terminal: "종결 회차", purchase: "확정 매입", amount: "매입액", average: "평균가", supplierReturnRate: "매입처 반품률", defectRate: "검수 불량률", customerReturnRate: "고객 반품 확정률" },
    pricePolicy: { title: "가격 정책 결과", subtitle: "매입 확정 당시 저장한 기준가와 실제 확정가의 관계를 비교합니다.", mode: "입력 방식", purchase: "매입", amount: "매입액", average: "평균가", reference: "기준가 확인", adjustment: "평균 조정", direction: "상승 / 동일 / 하락", rate: "기준가 적용", override: "기준가 조정", manual: "수동 입력", unknown: "과거 미기록" },
    inspection: { title: "입고 검수 품질", subtitle: "정확한 입고 회차에 연결된 검수만 집계합니다.", defectRate: "검수 불량률", sample: "검수 연결 표본", sampleDescription: "실제 하자 {count, number}건", appearance: "외관 하자 항목", appearanceDescription: "한 회차에 여러 하자 항목이 기록될 수 있습니다.", function: "기능 하자 항목", functionDescription: "항목 비중은 검수 기기 비중과 다를 수 있습니다." },
    leadTime: { title: "매입 처리시간", subtitle: "중앙값을 주 값으로, P90과 제외 이상치를 함께 표시합니다.", receivedToInspection: "입고 → 마지막 검수", inspectionToOutcome: "마지막 검수 → 종결", receivedToOutcome: "입고 → 종결" },
    loading: { initial: "매입 통계를 불러오는 중입니다.", aggregating: "매입 데이터를 집계하고 있습니다.", error: "매입 통계를 불러오지 못했습니다.", retry: "다시 시도", refresh: "같은 조건으로 통계를 다시 확인하고 있습니다. 현재 결과는 계속 표시합니다." },
    count: "{count, number}건"
  },
  returns: {
    fallback: { loadFailed: "반품 통계를 불러오지 못했습니다." },
    presentation: { aggregating: "집계 중", comparisonUnavailable: "비교 불가", comparisonUnavailableDetail: "현재와 직전 성숙 cohort가 모두 있어야 비교할 수 있습니다.", previousCohort: "직전 성숙 cohort 대비" },
    coverage: {
      deviceCount: "{count, number}대",
      claimAfter30: "판매 후 30일을 초과한 반품 연결 {count, number}건", claimBeforeSale: "판매일보다 먼저 기록된 반품 연결 {count, number}건", confirmedInspection: "확정 검수 연결", costCoverage: "매입 원가 확인 범위", eventCount: "조회 이벤트 {count, number}건", eventStart: "이벤트 기록 시작", generatedAt: "생성 시각", inspectionDescription: "반품 연결 PG {count, number}대", invalidTime: "시간 순서 이상으로 소요 시간에서 제외한 건 {count, number}건", lastObserved: "마지막 반품 관찰", linkDescription: "{detail} · 확정 {confirmed, number} · 고유 키 {unique, number}", linkRate: "반품 접수 연결률", linkedSales: "연결된 판매 이력", linkedSalesDescription: "판매 cohort {count, number}건", missingTime: "외부 접수 시각이 없거나 잘못된 건 {count, number}건", observed: "반품 {returns, number} · 취소 {cancellations, number} · 교환 {exchanges, number}", periodAll: "선택 기간 전체", priceCount: "{available, number} / {total, number}건", priceCoverage: "판매가 확인 범위", subtitle: "반품 통계를 해석하기 전에 수집 기간과 연결·가격·검수 범위를 확인하세요.", success: "조회 범위에서 별도로 확인할 연결·시간 이상이 없습니다.", title: "데이터 기준과 신뢰도", unlinkedReceipt: "판매 이력이 연결되지 않은 반품 접수 {count, number}건", unmatchedWithdrawal: "판매 이력과 연결되지 않은 철회 기록 {count, number}건", warning: "통계에서 확인이 필요한 데이터가 있습니다.", ambiguousReceipt: "연결 후보가 중복된 반품 접수 {count, number}건" },
    summary: { associatedSales: "반품 연관 판매액", previous: "직전 cohort 대비", previousDescription: "{detail} · 직전 {value}", recovery: "재판매 가능 회복률", requestRate: "30일 고객 반품 요청률", vendorFault: "판매자 귀책 비중" },
    overview: { amount: "연관 판매액", completed: "반품 완료", connected: "연결된 접수", connectedSales: "연결된 판매 이력", count: "{count, number}건", linkedSales: "연결 판매", month: "접수 월", quantity: "수량", quantityValue: "수량 {count, number}개", receipts: "반품 접수", subtitle: "판매 후 고객 반품 접수의 규모와 월별 발생 흐름입니다.", title: "고객 반품 발생 개요", withdrawn: "철회", linkRate: "접수 연결률" },
    cohort: { days14: "14일", days30: "30일", days7: "7일", month: "판매 월", sample: "cohort 표본", sales: "판매", subtitle: "각 기간별 분자와 성숙한 판매 이력 분모를 함께 표시합니다.", title: "판매 cohort 고객 반품 요청률" },
    product: { amount: "연관 판매액", delta: "직전 대비", matureSales: "성숙 판매", model: "모델", rate30: "30일 요청률", recovery: "재판매 회복", returnSales: "반품 판매", saleGrade: "등급", sellerFault: "판매자 귀책", storage: "용량", subtitle: "현재 성숙 cohort의 상품 조합별 반품 요청률과 금액·귀책·회복 지표를 비교합니다.", title: "상품별 반품 비교" },
    inspection: { appearanceDefect: "외관 결함", confirmed: "확정 검수", description: "확정 검수와 연결된 PG만 재판매 가능 여부에 포함합니다.", fault: "귀책 구분", functionDefect: "기능 결함", hold: "보류", linkedPg: "연결 반품 PG", matrixDescription: "반품 사유와 실제 검수 결과를 연결할 수 있는 범위만 표시합니다.", matrixTitle: "사유별 검수 결과", nonSellable: "판매 불가", reason: "반품 사유", recovery: "재판매 가능 회복률", resellable: "재판매 가능", title: "반품 검수 결과", unit: "{count, number}대", inspectedPg: "검수 PG" },
    economics: { associatedCost: "연결 판매의 매입 원가", associatedSales: "반품 연관 판매액", description: "가격이 확인된 연결 판매 이력만 합산하며, 가격이 없으면 0원이 아니라 ‘-’로 표시합니다.", nonSellableCost: "판매 불가·보류 자산 원가", recoveredCost: "재판매 가능 자산 원가", title: "반품 연관 금액" },
    leadTime: { description: "중앙값을 대표값으로 표시하고 P90·표본·제외 이상치를 함께 제공합니다.", observationToApproval: "최초 관찰 → 승인 요청", observationToFinal: "최초 관찰 → 내부 확정", receiptToObservation: "외부 접수 → 최초 관찰", title: "처리 소요 시간" },
    cancellation: { count: "취소 접수", description: "판매 후 고객 반품과 섞지 않고 별도 모집단으로 표시합니다.", month: "월별 발생", products: "취소 상품", quantity: "취소 수량", reasons: "취소 사유", title: "출고 전 취소", unit: "{count, number}개" },
    exchange: { description: "교환 접수·결과와 완료까지의 시간을 별도 모집단으로 표시합니다.", duration: "종결 소요 시간", fault: "귀책 구분", reasons: "교환 사유", receipts: "교환 접수", results: "교환 결과", title: "교환" },
    loading: { aggregating: "반품 데이터를 집계하고 있습니다.", error: "반품 통계를 불러오지 못했습니다.", initial: "반품 통계를 불러오는 중입니다.", refresh: "같은 조건으로 통계를 다시 확인하고 있습니다. 현재 결과는 계속 표시합니다.", retry: "다시 시도" },
  },
} as const;

export type StatisticsMessages = typeof statisticsKo;
