export const suppliesKo = {
  message: { loading: "비품관리 데이터를 불러오는 중입니다.", loaded: "비품관리 데이터를 불러왔습니다.", loadFailed: "비품관리 데이터를 불러오지 못했습니다.", actionFailed: "비품관리 작업에 실패했습니다.", actionComplete: "비품관리 작업을 완료했습니다.", supplySaved: "비품 정보를 저장했습니다.", movementRecorded: "비품 재고 수량 변동을 저장했습니다.", consumptionRuleSaved: "비품 소요 계산 규칙을 저장했습니다.", forecastCalculated: "비품 소요예측을 계산했습니다.", reorderSuggestionsCreated: "비품 재구매 추천을 생성했습니다.", reorderStatusUpdated: "비품 재구매 상태를 수정했습니다.", actionCompleteRefresh: "{message} 전체 현황은 새로고침해 확인하세요.", unsupportedRuleFilters: "{trigger} 계산 기준에서는 {filters} 필터를 사용할 수 없습니다." },
  unsaved: { reorderTarget: "재구매 요청 #{id}", reorderEdit: "재구매 요청 수정", ruleEdit: "비품 소요 규칙 수정", ruleNew: "새 비품 소요 규칙", selectedSupply: "선택 비품", supplyTarget: "{name} 비품 정보", supplyNew: "새 비품 정보", movementTarget: "{name} 수량 기록", movement: "비품 수량 기록", openSupply: "{name} 비품 열기", resetSupply: "새 비품 입력으로 초기화", switchMovement: "{name} 수량 기록으로 전환", clearMovement: "수량 기록 비품 선택 해제", openRule: "선택한 비품 소요 규칙 열기", openReorder: "재구매 요청 #{id} 열기" },
  actions: { reset: "입력 초기화", save: "저장", select: "선택" },
  form: { active: "사용 중인 비품", baseUnit: "기본단위", category: "분류", code: "비품 코드", consumptionPolicy: "출고 차감 시점", defaultSupplier: "매입처", editTitle: "비품 수정", inventoryLocation: "위치", lossRate: "불량소모율(%)", maxLeadTime: "최대 리드타임", memo: "메모", minLeadTime: "최소 리드타임", minimumOrderQuantity: "최소주문 수량", name: "비품명", newTitle: "비품 등록", orderUnit: "주문단위", orderUnitQuantity: "주문단위 수량", reservedQuantity: "예약 수량", targetStockDays: "목표 재고일수", unitCost: "단가" },
  forecast: { actual: "실제 소요", averageDaily: "일평균", calculate: "소요예측 계산", calculation: "예측 계산", date: "계산일", days: "{elapsed, number} / {lookback, number}일", difference: "차이", elapsed: "경과", empty: "계산된 소요예측이 없습니다.", errorRate: "오차율", lookback: "조회 기준 기간", predicted: "예측 소요", recommended: "권장구매", reorderPoint: "재주문점", result: "소요예측 결과", safetyStock: "안전재고", stockout: "재고소진 예상", targetStock: "목표재고", validation: "예측 검증", validationEmpty: "검증할 소요예측 기록이 없습니다.", validationHint: "계산일 이후 실제 소모 이력이 쌓이면 예측 소요와 실제 소요를 비교합니다. 오늘 계산한 예측은 하루 이상 지나야 검증할 수 있습니다.", validationPeriod: "검증 기간", validationStatus: "판정" },
  validationState: { PENDING: "검증 대기", NO_USAGE: "사용 없음", GOOD: "양호", WARNING: "주의", HIGH_ERROR: "오차 큼" },
  trigger: { PURCHASED_DEVICE: "매입 확정 기기", SHIPMENT_CREATED: "출고/송장 건", ORDER_ITEM: "주문 상품 수량", PACKING_COMPLETED: "재고실사 포장 완료", RETURN_RECEIVED: "반품 입고 건" },
  inventory: { active: "사용", empty: "등록된 비품이 없습니다.", inactive: "비활성", title: "비품 재고 목록" },
  movement: { empty: "최근 수량 이력이 없습니다.", formTitle: "수량 기록", save: "수량 기록 저장", selectSupply: "비품 선택", title: "최근 수량 이력", type: { adjustment: "조정", consumed: "사용", discarded: "폐기", inbound: "입고", returned: "반납" } },
  policy: { confirmedOnly: "포장 검증 완료 시만 차감", prepackAllowed: "선포장 또는 포장 검증 시 차감" },
  reorder: { action: "작업", createSuggestions: "추천 생성", editTitle: "재구매 상태 수정", empty: "재구매 요청이 없습니다.", expectedUnitCost: "예상 단가", forecastOutdated: "예측 갱신 필요", historyMore: "완료 이력 더 보기", latestRecommended: "최신 권장: {quantity}", listTitle: "재구매 요청 목록", loading: "불러오는 중", ordered: "주문", orderedQuantity: "주문 수량", reason: "사유 / 메모", received: "입고", receivedQuantity: "입고 수량", recommended: "권장", recommendedTargets: "권장 구매 대상", request: "요청", requestId: "재구매 요청", requestedQuantity: "요청 수량", save: "상태 저장", saveHint: "상태를 입고 완료로 저장하고 입고 수량이 있으면 비품 재고가 자동 증가합니다.", select: "선택", status: "상태", statusValue: { approved: "승인", cancelled: "취소", ordered: "주문 완료", received: "입고 완료", requested: "구매 요청", suggested: "시스템 추천" }, supplier: "거래처" },
  rule: { active: "사용", allItems: "이 계산 기준은 별도 상품 필터 없이 전체 건을 집계합니다.", calculationBasis: "계산 기준", filterField: { channel: "채널", inventoryStatus: "재고상태", model: "기종", saleGrade: "판매등급", warranty: "보증" }, filterForm: { channel: "채널 필터", inventoryStatus: "재고상태 필터", model: "기종 필터", saleGrade: "판매등급 필터", warranty: "보증 필터" }, editTitle: "소요 규칙 수정", empty: "등록된 소요 규칙이 없습니다.", filter: "필터", memo: "메모", newTitle: "소요 규칙 등록", quantity: "소요량", quantityPerUnit: "1건당 소요량", registered: "등록된 소요 규칙", save: "규칙 저장", selectSupply: "비품 선택", status: "상태", tab: "소요 규칙", trigger: "기준", inactive: "비활성", edit: "수정" },
  tabs: { forecast: "예측 결과", rules: "소요 규칙", validation: "예측 검증" },
  summary: { active: "활성 비품", belowReorder: "재주문점 이하", openReorders: "열린 재구매", registered: "등록 비품" },
  table: { action: "작업", after: "변경 후", available: "사용가능", before: "변경 전", category: "분류", code: "코드", current: "현재", date: "일시", location: "위치", name: "비품명", operator: "작업자", policy: "출고 차감 시점", quantity: "수량", reason: "사유", reserved: "예약", status: "상태", supply: "비품", type: "유형" },
} as const;

export type SuppliesMessages = typeof suppliesKo;
