// Source: quickhack_color_model_links_20261006.csv (SHA-256 59498cd475376d9317ee8c0123f0c5615ab4ebe089d87ee3897938986ab606c8).
// Canonical keys, labels, active states and model-color links only; source database IDs are intentionally omitted.
export const INITIAL_COLOR_OPTIONS = [
  { optionKey: "블랙", label: "블랙", isActive: true },
  { optionKey: "화이트", label: "화이트", isActive: true },
  { optionKey: "그레이", label: "그레이", isActive: true },
  { optionKey: "실버", label: "실버", isActive: true },
  { optionKey: "블루", label: "블루", isActive: true },
  { optionKey: "그린", label: "그린", isActive: true },
  { optionKey: "핑크", label: "핑크", isActive: true },
  { optionKey: "퍼플", label: "퍼플", isActive: true },
  { optionKey: "레드", label: "레드", isActive: true },
  { optionKey: "크림", label: "크림", isActive: true },
  { optionKey: "팬텀 블랙", label: "팬텀 블랙", isActive: true },
  { optionKey: "팬텀 화이트", label: "팬텀 화이트", isActive: true },
  { optionKey: "핑크 골드", label: "핑크 골드", isActive: false },
  { optionKey: "그라파이트", label: "그라파이트", isActive: true },
  { optionKey: "스카이 블루", label: "스카이 블루", isActive: true },
  { optionKey: "바이올렛", label: "바이올렛", isActive: true },
  { optionKey: "보라 퍼플", label: "보라 퍼플", isActive: true },
  { optionKey: "버건디", label: "버건디", isActive: true },
  { optionKey: "라벤더", label: "라벤더", isActive: true },
  { optionKey: "라임", label: "라임", isActive: true },
  { optionKey: "민트", label: "민트", isActive: true },
  { optionKey: "인디고", label: "인디고", isActive: true },
  { optionKey: "탠저린", label: "탠저린", isActive: true },
  { optionKey: "오닉스 블랙", label: "오닉스 블랙", isActive: true },
  { optionKey: "마블 그레이", label: "마블 그레이", isActive: true },
  { optionKey: "앰버 옐로우", label: "앰버 옐로우", isActive: true },
  { optionKey: "코발트 바이올렛", label: "코발트 바이올렛", isActive: true },
  { optionKey: "샌드스톤 오렌지", label: "샌드스톤 오렌지", isActive: true },
  { optionKey: "사파이어 블루", label: "사파이어 블루", isActive: true },
  { optionKey: "제이드 그린", label: "제이드 그린", isActive: true },
  { optionKey: "옐로우", label: "옐로우", isActive: true },
  { optionKey: "티타늄 블랙", label: "티타늄 블랙", isActive: true },
  { optionKey: "티타늄 옐로우", label: "티타늄 옐로우", isActive: true },
  { optionKey: "티타늄 그레이", label: "티타늄 그레이", isActive: true },
  { optionKey: "티타늄 바이올렛", label: "티타늄 바이올렛", isActive: true },
  { optionKey: "티타늄 오렌지", label: "티타늄 오렌지", isActive: true },
  { optionKey: "티타늄 블루", label: "티타늄 블루", isActive: true },
  { optionKey: "티타늄 그린", label: "티타늄 그린", isActive: true },
  { optionKey: "실버 쉐도우", label: "실버 쉐도우", isActive: true },
  { optionKey: "네이비", label: "네이비", isActive: true },
  { optionKey: "아이스블루", label: "아이스블루", isActive: true },
  { optionKey: "블루블랙", label: "블루블랙", isActive: true },
  { optionKey: "핑크골드", label: "핑크골드", isActive: true },
  { optionKey: "코랄레드", label: "코랄레드", isActive: true },
  { optionKey: "티타늄 아이스블루", label: "티타늄 아이스블루", isActive: true },
  { optionKey: "티타늄 실버", label: "티타늄 실버", isActive: true },
  { optionKey: "티타늄 제트블랙", label: "티타늄 제트블랙", isActive: true },
  { optionKey: "티타늄 실버블루", label: "티타늄 실버블루", isActive: true },
  { optionKey: "티타늄 화이트실버", label: "티타늄 화이트실버", isActive: true },
  { optionKey: "티타늄 핑크골드", label: "티타늄 핑크골드", isActive: true },
  { optionKey: "티타늄 제이드그린", label: "티타늄 제이드그린", isActive: true },
  { optionKey: "제트블랙", label: "제트블랙", isActive: true },
  { optionKey: "블루 블랙", label: "블루 블랙", isActive: true },
  { optionKey: "라이트 블루", label: "라이트 블루", isActive: true },
  { optionKey: "라이트 그레이", label: "라이트 그레이", isActive: true },
  { optionKey: "라이트 그린", label: "라이트 그린", isActive: true },
  { optionKey: "피치", label: "피치", isActive: true },
  { optionKey: "다크 레드", label: "다크 레드", isActive: true },
  { optionKey: "어썸 블랙", label: "어썸 블랙", isActive: true },
  { optionKey: "어썸 화이트", label: "어썸 화이트", isActive: true },
  { optionKey: "어썸 블루", label: "어썸 블루", isActive: true },
  { optionKey: "어썸 피치", label: "어썸 피치", isActive: true },
  { optionKey: "어썸 그라파이트", label: "어썸 그라파이트", isActive: true },
  { optionKey: "어썸 실버", label: "어썸 실버", isActive: true },
  { optionKey: "어썸 바이올렛", label: "어썸 바이올렛", isActive: true },
  { optionKey: "어썸 라임", label: "어썸 라임", isActive: true },
  { optionKey: "어썸 네이비", label: "어썸 네이비", isActive: true },
  { optionKey: "어썸 아이스블루", label: "어썸 아이스블루", isActive: true },
  { optionKey: "어썸 라일락", label: "어썸 라일락", isActive: true },
  { optionKey: "어썸 레몬", label: "어썸 레몬", isActive: true },
  { optionKey: "딥 그린", label: "딥 그린", isActive: true },
  { optionKey: "오렌지 코퍼", label: "오렌지 코퍼", isActive: true },
  { optionKey: "헤이즈 오렌지", label: "헤이즈 오렌지", isActive: true },
  { optionKey: "어썸 라이트그레이", label: "어썸 라이트그레이", isActive: true },
  { optionKey: "어썸 올리브", label: "어썸 올리브", isActive: true },
  { optionKey: "어썸 핑크", label: "어썸 핑크", isActive: true },
  { optionKey: "오렌지", label: "오렌지", isActive: true },
  { optionKey: "다크 블루", label: "다크 블루", isActive: true },
  { optionKey: "크래프티드 블랙", label: "크래프티드 블랙", isActive: true },
  { optionKey: "블루 쉐도우", label: "블루 쉐도우", isActive: true },
  { optionKey: "베이지", label: "베이지", isActive: true },
  { optionKey: "그레이 그린", label: "그레이 그린", isActive: true },
] as const;

export const INITIAL_COLOR_MODELS = [
  { optionKey: "SM-S911N", label: "Galaxy S23", isActive: true },
  { optionKey: "SM-S916N", label: "Galaxy S23+", isActive: true },
  { optionKey: "SM-S918N", label: "Galaxy S23 Ultra", isActive: true },
  { optionKey: "SM-S921N", label: "Galaxy S24", isActive: true },
  { optionKey: "SM-S926N", label: "Galaxy S24+", isActive: true },
  { optionKey: "SM-S928N", label: "Galaxy S24 Ultra", isActive: true },
  { optionKey: "SM-S931N", label: "Galaxy S25", isActive: true },
  { optionKey: "SM-S936N", label: "Galaxy S25+", isActive: true },
  { optionKey: "SM-S938N", label: "Galaxy S25 Ultra", isActive: true },
  { optionKey: "SM-S711N", label: "Galaxy S23 FE", isActive: true },
  { optionKey: "SM-S721N", label: "Galaxy S24 FE", isActive: true },
  { optionKey: "SM-F731N", label: "Galaxy Z Flip5", isActive: true },
  { optionKey: "SM-F741N", label: "Galaxy Z Flip6", isActive: true },
  { optionKey: "SM-F766N", label: "Galaxy Z Flip7", isActive: true },
  { optionKey: "SM-F946N", label: "Galaxy Z Fold5", isActive: true },
  { optionKey: "SM-F956N", label: "Galaxy Z Fold6", isActive: true },
  { optionKey: "SM-A156N", label: "Galaxy A15", isActive: false },
  { optionKey: "SM-A256N", label: "Galaxy A25", isActive: true },
  { optionKey: "SM-A346N", label: "Galaxy A34", isActive: true },
  { optionKey: "SM-A165N", label: "Galaxy A16", isActive: false },
  { optionKey: "SM-A235N", label: "Galaxy A23", isActive: true },
  { optionKey: "SM-A356N", label: "Galaxy A35", isActive: true },
  { optionKey: "SM-A556N", label: "Galaxy A55", isActive: true },
  { optionKey: "SM-A245N", label: "Galaxy A24", isActive: true },
  { optionKey: "SM-A546S", label: "Galaxy Quantum4", isActive: false },
  { optionKey: "SM-A556S", label: "Galaxy Quantum5", isActive: true },
  { optionKey: "SM-A566S", label: "Galaxy Quantum6", isActive: true },
  { optionKey: "SM-A236L", label: "Galaxy Buddy2", isActive: true },
  { optionKey: "SM-E426S", label: "Galaxy Wide5", isActive: true },
  { optionKey: "SM-A136S", label: "Galaxy Wide6", isActive: true },
  { optionKey: "SM-M156S", label: "Galaxy Wide7", isActive: true },
  { optionKey: "SM-M446K", label: "Galaxy Jump3", isActive: true },
  { optionKey: "SM-M366K", label: "Galaxy Jump4", isActive: true },
  { optionKey: "Galaxy S22", label: "Galaxy S22", isActive: false },
  { optionKey: "Galaxy S22+", label: "Galaxy S22+", isActive: false },
  { optionKey: "Galaxy S22 Ultra", label: "Galaxy S22 Ultra", isActive: false },
  { optionKey: "Galaxy S25 FE", label: "Galaxy S25 FE", isActive: false },
  { optionKey: "Galaxy S25 Edge", label: "Galaxy S25 Edge", isActive: false },
  { optionKey: "Galaxy S26", label: "Galaxy S26", isActive: false },
  { optionKey: "Galaxy S26+", label: "Galaxy S26+", isActive: false },
  { optionKey: "Galaxy S26 Ultra", label: "Galaxy S26 Ultra", isActive: false },
  { optionKey: "Galaxy A33", label: "Galaxy A33", isActive: false },
  { optionKey: "Galaxy Z Fold4", label: "Galaxy Z Fold4", isActive: false },
  { optionKey: "Galaxy Z Fold7", label: "Galaxy Z Fold7", isActive: false },
] as const;

export const INITIAL_MODEL_COLOR_LINKS = [
  { modelKey: "SM-A165N", colorKey: "블랙", sortOrder: 500, isActive: true },
  { modelKey: "SM-A235N", colorKey: "블랙", sortOrder: 500, isActive: true },
  { modelKey: "SM-A245N", colorKey: "블랙", sortOrder: 500, isActive: true },
  { modelKey: "SM-M446K", colorKey: "블랙", sortOrder: 500, isActive: true },
  { modelKey: "SM-M366K", colorKey: "블랙", sortOrder: 500, isActive: true },
  { modelKey: "Galaxy S26", colorKey: "블랙", sortOrder: 500, isActive: true },
  { modelKey: "Galaxy S26 Ultra", colorKey: "블랙", sortOrder: 500, isActive: true },
  { modelKey: "Galaxy S26+", colorKey: "블랙", sortOrder: 500, isActive: true },
  { modelKey: "SM-A136S", colorKey: "블랙", sortOrder: 500, isActive: true },
  { modelKey: "SM-A235N", colorKey: "화이트", sortOrder: 490, isActive: true },
  { modelKey: "SM-M446K", colorKey: "화이트", sortOrder: 490, isActive: true },
  { modelKey: "Galaxy S25 FE", colorKey: "화이트", sortOrder: 490, isActive: true },
  { modelKey: "Galaxy S26", colorKey: "화이트", sortOrder: 490, isActive: true },
  { modelKey: "Galaxy S26 Ultra", colorKey: "화이트", sortOrder: 490, isActive: true },
  { modelKey: "Galaxy S26+", colorKey: "화이트", sortOrder: 490, isActive: true },
  { modelKey: "SM-E426S", colorKey: "화이트", sortOrder: 490, isActive: true },
  { modelKey: "SM-A136S", colorKey: "화이트", sortOrder: 490, isActive: true },
  { modelKey: "SM-F741N", colorKey: "화이트", sortOrder: 490, isActive: true },
  { modelKey: "SM-F956N", colorKey: "화이트", sortOrder: 490, isActive: true },
  { modelKey: "SM-S721N", colorKey: "그레이", sortOrder: 250, isActive: true },
  { modelKey: "SM-E426S", colorKey: "그레이", sortOrder: 250, isActive: true },
  { modelKey: "SM-M156S", colorKey: "그레이", sortOrder: 250, isActive: true },
  { modelKey: "SM-F731N", colorKey: "그레이", sortOrder: 250, isActive: true },
  { modelKey: "SM-F946N", colorKey: "그레이", sortOrder: 250, isActive: true },
  { modelKey: "SM-A245N", colorKey: "실버", sortOrder: 560, isActive: true },
  { modelKey: "SM-A156N", colorKey: "블루", sortOrder: 260, isActive: true },
  { modelKey: "SM-A235N", colorKey: "블루", sortOrder: 260, isActive: true },
  { modelKey: "SM-A256N", colorKey: "블루", sortOrder: 260, isActive: true },
  { modelKey: "SM-S721N", colorKey: "블루", sortOrder: 260, isActive: true },
  { modelKey: "SM-E426S", colorKey: "블루", sortOrder: 260, isActive: true },
  { modelKey: "SM-F731N", colorKey: "블루", sortOrder: 260, isActive: true },
  { modelKey: "SM-F741N", colorKey: "블루", sortOrder: 260, isActive: true },
  { modelKey: "SM-F946N", colorKey: "블루", sortOrder: 260, isActive: true },
  { modelKey: "Galaxy S22", colorKey: "그린", sortOrder: 40, isActive: true },
  { modelKey: "Galaxy S22 Ultra", colorKey: "그린", sortOrder: 40, isActive: true },
  { modelKey: "Galaxy S22+", colorKey: "그린", sortOrder: 40, isActive: true },
  { modelKey: "SM-S911N", colorKey: "그린", sortOrder: 40, isActive: true },
  { modelKey: "SM-S918N", colorKey: "그린", sortOrder: 40, isActive: true },
  { modelKey: "SM-S916N", colorKey: "그린", sortOrder: 40, isActive: true },
  { modelKey: "SM-A136S", colorKey: "그린", sortOrder: 40, isActive: true },
  { modelKey: "SM-F731N", colorKey: "그린", sortOrder: 40, isActive: true },
  { modelKey: "SM-F956N", colorKey: "핑크", sortOrder: 830, isActive: true },
  { modelKey: "SM-S711N", colorKey: "퍼플", sortOrder: 140, isActive: true },
  { modelKey: "Galaxy S22 Ultra", colorKey: "레드", sortOrder: 110, isActive: true },
  { modelKey: "SM-S918N", colorKey: "레드", sortOrder: 110, isActive: true },
  { modelKey: "Galaxy S22", colorKey: "크림", sortOrder: 60, isActive: true },
  { modelKey: "Galaxy S22+", colorKey: "크림", sortOrder: 60, isActive: true },
  { modelKey: "SM-S911N", colorKey: "크림", sortOrder: 60, isActive: true },
  { modelKey: "SM-S711N", colorKey: "크림", sortOrder: 60, isActive: true },
  { modelKey: "SM-S918N", colorKey: "크림", sortOrder: 60, isActive: true },
  { modelKey: "SM-S916N", colorKey: "크림", sortOrder: 60, isActive: true },
  { modelKey: "SM-F731N", colorKey: "크림", sortOrder: 60, isActive: true },
  { modelKey: "SM-F946N", colorKey: "크림", sortOrder: 60, isActive: true },
  { modelKey: "Galaxy S22", colorKey: "팬텀 블랙", sortOrder: 10, isActive: true },
  { modelKey: "Galaxy S22 Ultra", colorKey: "팬텀 블랙", sortOrder: 10, isActive: true },
  { modelKey: "Galaxy S22+", colorKey: "팬텀 블랙", sortOrder: 10, isActive: true },
  { modelKey: "SM-S911N", colorKey: "팬텀 블랙", sortOrder: 10, isActive: true },
  { modelKey: "SM-S918N", colorKey: "팬텀 블랙", sortOrder: 10, isActive: true },
  { modelKey: "SM-S916N", colorKey: "팬텀 블랙", sortOrder: 10, isActive: true },
  { modelKey: "Galaxy Z Fold4", colorKey: "팬텀 블랙", sortOrder: 10, isActive: true },
  { modelKey: "SM-F946N", colorKey: "팬텀 블랙", sortOrder: 10, isActive: true },
  { modelKey: "Galaxy S22", colorKey: "팬텀 화이트", sortOrder: 20, isActive: true },
  { modelKey: "Galaxy S22 Ultra", colorKey: "팬텀 화이트", sortOrder: 20, isActive: true },
  { modelKey: "Galaxy S22+", colorKey: "팬텀 화이트", sortOrder: 20, isActive: true },
  { modelKey: "Galaxy S22", colorKey: "핑크 골드", sortOrder: 30, isActive: true },
  { modelKey: "Galaxy S22+", colorKey: "핑크 골드", sortOrder: 30, isActive: true },
  { modelKey: "Galaxy S26", colorKey: "핑크 골드", sortOrder: 30, isActive: true },
  { modelKey: "Galaxy S26 Ultra", colorKey: "핑크 골드", sortOrder: 30, isActive: true },
  { modelKey: "Galaxy S26+", colorKey: "핑크 골드", sortOrder: 30, isActive: true },
  { modelKey: "Galaxy S22", colorKey: "그라파이트", sortOrder: 50, isActive: true },
  { modelKey: "Galaxy S22 Ultra", colorKey: "그라파이트", sortOrder: 50, isActive: true },
  { modelKey: "Galaxy S22+", colorKey: "그라파이트", sortOrder: 50, isActive: true },
  { modelKey: "SM-S911N", colorKey: "그라파이트", sortOrder: 50, isActive: true },
  { modelKey: "SM-S711N", colorKey: "그라파이트", sortOrder: 50, isActive: true },
  { modelKey: "SM-S918N", colorKey: "그라파이트", sortOrder: 50, isActive: true },
  { modelKey: "SM-S916N", colorKey: "그라파이트", sortOrder: 50, isActive: true },
  { modelKey: "SM-S721N", colorKey: "그라파이트", sortOrder: 50, isActive: true },
  { modelKey: "SM-F731N", colorKey: "그라파이트", sortOrder: 50, isActive: true },
  { modelKey: "Galaxy S22", colorKey: "스카이 블루", sortOrder: 70, isActive: true },
  { modelKey: "Galaxy S22 Ultra", colorKey: "스카이 블루", sortOrder: 70, isActive: true },
  { modelKey: "Galaxy S22+", colorKey: "스카이 블루", sortOrder: 70, isActive: true },
  { modelKey: "SM-S918N", colorKey: "스카이 블루", sortOrder: 70, isActive: true },
  { modelKey: "Galaxy S26", colorKey: "스카이 블루", sortOrder: 70, isActive: true },
  { modelKey: "Galaxy S26 Ultra", colorKey: "스카이 블루", sortOrder: 70, isActive: true },
  { modelKey: "Galaxy S26+", colorKey: "스카이 블루", sortOrder: 70, isActive: true },
  { modelKey: "Galaxy S22", colorKey: "바이올렛", sortOrder: 80, isActive: true },
  { modelKey: "Galaxy S22+", colorKey: "바이올렛", sortOrder: 80, isActive: true },
  { modelKey: "Galaxy S22", colorKey: "보라 퍼플", sortOrder: 90, isActive: true },
  { modelKey: "Galaxy S22+", colorKey: "보라 퍼플", sortOrder: 90, isActive: true },
  { modelKey: "Galaxy S22 Ultra", colorKey: "버건디", sortOrder: 100, isActive: true },
  { modelKey: "Galaxy Z Fold4", colorKey: "버건디", sortOrder: 100, isActive: true },
  { modelKey: "SM-S911N", colorKey: "라벤더", sortOrder: 120, isActive: true },
  { modelKey: "SM-S918N", colorKey: "라벤더", sortOrder: 120, isActive: true },
  { modelKey: "SM-S916N", colorKey: "라벤더", sortOrder: 120, isActive: true },
  { modelKey: "SM-F731N", colorKey: "라벤더", sortOrder: 120, isActive: true },
  { modelKey: "SM-S911N", colorKey: "라임", sortOrder: 130, isActive: true },
  { modelKey: "SM-S918N", colorKey: "라임", sortOrder: 130, isActive: true },
  { modelKey: "SM-S916N", colorKey: "라임", sortOrder: 130, isActive: true },
  { modelKey: "SM-S711N", colorKey: "민트", sortOrder: 150, isActive: true },
  { modelKey: "SM-S721N", colorKey: "민트", sortOrder: 150, isActive: true },
  { modelKey: "SM-S931N", colorKey: "민트", sortOrder: 150, isActive: true },
  { modelKey: "SM-S936N", colorKey: "민트", sortOrder: 150, isActive: true },
  { modelKey: "SM-F731N", colorKey: "민트", sortOrder: 150, isActive: true },
  { modelKey: "SM-F741N", colorKey: "민트", sortOrder: 150, isActive: true },
  { modelKey: "SM-F766N", colorKey: "민트", sortOrder: 150, isActive: true },
  { modelKey: "Galaxy Z Fold7", colorKey: "민트", sortOrder: 150, isActive: true },
  { modelKey: "SM-S711N", colorKey: "인디고", sortOrder: 160, isActive: true },
  { modelKey: "SM-S711N", colorKey: "탠저린", sortOrder: 170, isActive: true },
  { modelKey: "SM-S921N", colorKey: "오닉스 블랙", sortOrder: 180, isActive: true },
  { modelKey: "SM-S926N", colorKey: "오닉스 블랙", sortOrder: 180, isActive: true },
  { modelKey: "SM-S921N", colorKey: "마블 그레이", sortOrder: 190, isActive: true },
  { modelKey: "SM-S926N", colorKey: "마블 그레이", sortOrder: 190, isActive: true },
  { modelKey: "SM-S921N", colorKey: "앰버 옐로우", sortOrder: 200, isActive: true },
  { modelKey: "SM-S926N", colorKey: "앰버 옐로우", sortOrder: 200, isActive: true },
  { modelKey: "SM-S921N", colorKey: "코발트 바이올렛", sortOrder: 210, isActive: true },
  { modelKey: "SM-S926N", colorKey: "코발트 바이올렛", sortOrder: 210, isActive: true },
  { modelKey: "Galaxy S26", colorKey: "코발트 바이올렛", sortOrder: 210, isActive: true },
  { modelKey: "Galaxy S26 Ultra", colorKey: "코발트 바이올렛", sortOrder: 210, isActive: true },
  { modelKey: "Galaxy S26+", colorKey: "코발트 바이올렛", sortOrder: 210, isActive: true },
  { modelKey: "SM-S921N", colorKey: "샌드스톤 오렌지", sortOrder: 220, isActive: true },
  { modelKey: "SM-S926N", colorKey: "샌드스톤 오렌지", sortOrder: 220, isActive: true },
  { modelKey: "SM-S921N", colorKey: "사파이어 블루", sortOrder: 230, isActive: true },
  { modelKey: "SM-S926N", colorKey: "사파이어 블루", sortOrder: 230, isActive: true },
  { modelKey: "SM-S921N", colorKey: "제이드 그린", sortOrder: 240, isActive: true },
  { modelKey: "SM-S926N", colorKey: "제이드 그린", sortOrder: 240, isActive: true },
  { modelKey: "SM-A156N", colorKey: "옐로우", sortOrder: 270, isActive: true },
  { modelKey: "SM-A256N", colorKey: "옐로우", sortOrder: 270, isActive: true },
  { modelKey: "SM-S721N", colorKey: "옐로우", sortOrder: 270, isActive: true },
  { modelKey: "SM-F731N", colorKey: "옐로우", sortOrder: 270, isActive: true },
  { modelKey: "SM-F741N", colorKey: "옐로우", sortOrder: 270, isActive: true },
  { modelKey: "SM-S928N", colorKey: "티타늄 블랙", sortOrder: 280, isActive: true },
  { modelKey: "SM-S938N", colorKey: "티타늄 블랙", sortOrder: 280, isActive: true },
  { modelKey: "SM-S928N", colorKey: "티타늄 옐로우", sortOrder: 290, isActive: true },
  { modelKey: "SM-S928N", colorKey: "티타늄 그레이", sortOrder: 300, isActive: true },
  { modelKey: "SM-S938N", colorKey: "티타늄 그레이", sortOrder: 300, isActive: true },
  { modelKey: "SM-S928N", colorKey: "티타늄 바이올렛", sortOrder: 310, isActive: true },
  { modelKey: "SM-S928N", colorKey: "티타늄 오렌지", sortOrder: 320, isActive: true },
  { modelKey: "SM-S928N", colorKey: "티타늄 블루", sortOrder: 330, isActive: true },
  { modelKey: "SM-S928N", colorKey: "티타늄 그린", sortOrder: 340, isActive: true },
  { modelKey: "SM-S931N", colorKey: "실버 쉐도우", sortOrder: 350, isActive: true },
  { modelKey: "SM-S936N", colorKey: "실버 쉐도우", sortOrder: 350, isActive: true },
  { modelKey: "Galaxy S26", colorKey: "실버 쉐도우", sortOrder: 350, isActive: true },
  { modelKey: "Galaxy S26 Ultra", colorKey: "실버 쉐도우", sortOrder: 350, isActive: true },
  { modelKey: "Galaxy S26+", colorKey: "실버 쉐도우", sortOrder: 350, isActive: true },
  { modelKey: "SM-F741N", colorKey: "실버 쉐도우", sortOrder: 350, isActive: true },
  { modelKey: "SM-F956N", colorKey: "실버 쉐도우", sortOrder: 350, isActive: true },
  { modelKey: "Galaxy Z Fold7", colorKey: "실버 쉐도우", sortOrder: 350, isActive: true },
  { modelKey: "SM-S931N", colorKey: "네이비", sortOrder: 360, isActive: true },
  { modelKey: "Galaxy S25 FE", colorKey: "네이비", sortOrder: 360, isActive: true },
  { modelKey: "SM-S936N", colorKey: "네이비", sortOrder: 360, isActive: true },
  { modelKey: "SM-F956N", colorKey: "네이비", sortOrder: 360, isActive: true },
  { modelKey: "SM-S931N", colorKey: "아이스블루", sortOrder: 370, isActive: true },
  { modelKey: "Galaxy S25 FE", colorKey: "아이스블루", sortOrder: 370, isActive: true },
  { modelKey: "SM-S936N", colorKey: "아이스블루", sortOrder: 370, isActive: true },
  { modelKey: "SM-S931N", colorKey: "블루블랙", sortOrder: 380, isActive: true },
  { modelKey: "SM-S936N", colorKey: "블루블랙", sortOrder: 380, isActive: true },
  { modelKey: "SM-S931N", colorKey: "핑크골드", sortOrder: 390, isActive: true },
  { modelKey: "SM-S936N", colorKey: "핑크골드", sortOrder: 390, isActive: true },
  { modelKey: "SM-S931N", colorKey: "코랄레드", sortOrder: 400, isActive: true },
  { modelKey: "SM-S936N", colorKey: "코랄레드", sortOrder: 400, isActive: true },
  { modelKey: "SM-F766N", colorKey: "코랄레드", sortOrder: 400, isActive: true },
  { modelKey: "Galaxy S25 Edge", colorKey: "티타늄 아이스블루", sortOrder: 410, isActive: true },
  { modelKey: "Galaxy S25 Edge", colorKey: "티타늄 실버", sortOrder: 420, isActive: true },
  { modelKey: "Galaxy S25 Edge", colorKey: "티타늄 제트블랙", sortOrder: 430, isActive: true },
  { modelKey: "SM-S938N", colorKey: "티타늄 제트블랙", sortOrder: 430, isActive: true },
  { modelKey: "SM-S938N", colorKey: "티타늄 실버블루", sortOrder: 440, isActive: true },
  { modelKey: "SM-S938N", colorKey: "티타늄 화이트실버", sortOrder: 450, isActive: true },
  { modelKey: "SM-S938N", colorKey: "티타늄 핑크골드", sortOrder: 460, isActive: true },
  { modelKey: "SM-S938N", colorKey: "티타늄 제이드그린", sortOrder: 470, isActive: true },
  { modelKey: "Galaxy S25 FE", colorKey: "제트블랙", sortOrder: 480, isActive: true },
  { modelKey: "SM-F766N", colorKey: "제트블랙", sortOrder: 480, isActive: true },
  { modelKey: "Galaxy Z Fold7", colorKey: "제트블랙", sortOrder: 480, isActive: true },
  { modelKey: "SM-A156N", colorKey: "블루 블랙", sortOrder: 510, isActive: true },
  { modelKey: "SM-A256N", colorKey: "블루 블랙", sortOrder: 510, isActive: true },
  { modelKey: "SM-A156N", colorKey: "라이트 블루", sortOrder: 520, isActive: true },
  { modelKey: "SM-A256N", colorKey: "라이트 블루", sortOrder: 520, isActive: true },
  { modelKey: "SM-A236L", colorKey: "라이트 블루", sortOrder: 520, isActive: true },
  { modelKey: "SM-A136S", colorKey: "라이트 블루", sortOrder: 520, isActive: true },
  { modelKey: "SM-M156S", colorKey: "라이트 블루", sortOrder: 520, isActive: true },
  { modelKey: "SM-A165N", colorKey: "라이트 그레이", sortOrder: 530, isActive: true },
  { modelKey: "SM-A165N", colorKey: "라이트 그린", sortOrder: 540, isActive: true },
  { modelKey: "SM-A245N", colorKey: "라이트 그린", sortOrder: 540, isActive: true },
  { modelKey: "SM-M366K", colorKey: "라이트 그린", sortOrder: 540, isActive: true },
  { modelKey: "SM-A235N", colorKey: "피치", sortOrder: 550, isActive: true },
  { modelKey: "SM-F741N", colorKey: "피치", sortOrder: 550, isActive: true },
  { modelKey: "SM-A245N", colorKey: "다크 레드", sortOrder: 570, isActive: true },
  { modelKey: "Galaxy A33", colorKey: "어썸 블랙", sortOrder: 580, isActive: true },
  { modelKey: "Galaxy A33", colorKey: "어썸 화이트", sortOrder: 590, isActive: true },
  { modelKey: "SM-A546S", colorKey: "어썸 화이트", sortOrder: 590, isActive: true },
  { modelKey: "Galaxy A33", colorKey: "어썸 블루", sortOrder: 600, isActive: true },
  { modelKey: "Galaxy A33", colorKey: "어썸 피치", sortOrder: 610, isActive: true },
  { modelKey: "SM-A346N", colorKey: "어썸 그라파이트", sortOrder: 620, isActive: true },
  { modelKey: "SM-A546S", colorKey: "어썸 그라파이트", sortOrder: 620, isActive: true },
  { modelKey: "SM-A566S", colorKey: "어썸 그라파이트", sortOrder: 620, isActive: true },
  { modelKey: "SM-A346N", colorKey: "어썸 실버", sortOrder: 630, isActive: true },
  { modelKey: "SM-A346N", colorKey: "어썸 바이올렛", sortOrder: 640, isActive: true },
  { modelKey: "SM-A546S", colorKey: "어썸 바이올렛", sortOrder: 640, isActive: true },
  { modelKey: "SM-A346N", colorKey: "어썸 라임", sortOrder: 650, isActive: true },
  { modelKey: "SM-A546S", colorKey: "어썸 라임", sortOrder: 650, isActive: true },
  { modelKey: "SM-A356N", colorKey: "어썸 네이비", sortOrder: 660, isActive: true },
  { modelKey: "SM-A556N", colorKey: "어썸 네이비", sortOrder: 660, isActive: true },
  { modelKey: "SM-A556S", colorKey: "어썸 네이비", sortOrder: 660, isActive: true },
  { modelKey: "SM-A356N", colorKey: "어썸 아이스블루", sortOrder: 670, isActive: true },
  { modelKey: "SM-A556N", colorKey: "어썸 아이스블루", sortOrder: 670, isActive: true },
  { modelKey: "SM-A556S", colorKey: "어썸 아이스블루", sortOrder: 670, isActive: true },
  { modelKey: "SM-A356N", colorKey: "어썸 라일락", sortOrder: 680, isActive: true },
  { modelKey: "SM-A556N", colorKey: "어썸 라일락", sortOrder: 680, isActive: true },
  { modelKey: "SM-A556S", colorKey: "어썸 라일락", sortOrder: 680, isActive: true },
  { modelKey: "SM-A356N", colorKey: "어썸 레몬", sortOrder: 690, isActive: true },
  { modelKey: "SM-A556N", colorKey: "어썸 레몬", sortOrder: 690, isActive: true },
  { modelKey: "SM-A556S", colorKey: "어썸 레몬", sortOrder: 690, isActive: true },
  { modelKey: "SM-A236L", colorKey: "딥 그린", sortOrder: 700, isActive: true },
  { modelKey: "SM-A236L", colorKey: "오렌지 코퍼", sortOrder: 710, isActive: true },
  { modelKey: "SM-M366K", colorKey: "헤이즈 오렌지", sortOrder: 720, isActive: true },
  { modelKey: "SM-A566S", colorKey: "어썸 라이트그레이", sortOrder: 730, isActive: true },
  { modelKey: "SM-A566S", colorKey: "어썸 올리브", sortOrder: 740, isActive: true },
  { modelKey: "SM-A566S", colorKey: "어썸 핑크", sortOrder: 750, isActive: true },
  { modelKey: "SM-A136S", colorKey: "오렌지", sortOrder: 760, isActive: true },
  { modelKey: "SM-M156S", colorKey: "다크 블루", sortOrder: 770, isActive: true },
  { modelKey: "SM-F741N", colorKey: "크래프티드 블랙", sortOrder: 780, isActive: true },
  { modelKey: "SM-F956N", colorKey: "크래프티드 블랙", sortOrder: 780, isActive: true },
  { modelKey: "SM-F766N", colorKey: "블루 쉐도우", sortOrder: 790, isActive: true },
  { modelKey: "Galaxy Z Fold7", colorKey: "블루 쉐도우", sortOrder: 790, isActive: true },
  { modelKey: "Galaxy Z Fold4", colorKey: "베이지", sortOrder: 800, isActive: true },
  { modelKey: "Galaxy Z Fold4", colorKey: "그레이 그린", sortOrder: 810, isActive: true },
] as const;
