import type { Edge } from "@xyflow/react";
import {
  architectureEdge,
  backgroundStyle,
  dangerStyle,
  externalStyle,
  processingStyle,
  reliableStyle,
  requestStyle,
  successStyle,
  type ArchitectureDiagram,
  type ArchitectureIcon,
  type ArchitectureNode,
  type ArchitectureTone,
} from "./architecture-data";

type NodeInput = {
  id: string;
  x: number;
  y: number;
  eyebrow: string;
  title: string;
  description: string;
  detail: string;
  tone: ArchitectureTone;
  icon: ArchitectureIcon;
  width?: number;
};

function node(input: NodeInput): ArchitectureNode {
  return {
    id: input.id,
    type: "architecture",
    position: { x: input.x, y: input.y },
    style: { width: input.width ?? 230 },
    data: {
      eyebrow: input.eyebrow,
      title: input.title,
      description: input.description,
      detail: input.detail,
      tone: input.tone,
      icon: input.icon,
    },
  };
}

function link(
  id: string,
  source: string,
  target: string,
  options: Partial<Edge> = {}
) {
  return architectureEdge(id, source, target, {
    sourceHandle: "right-source",
    targetHandle: "left-target",
    ...options,
  });
}

const codeStructureDiagram: ArchitectureDiagram = {
  id: "code-structure",
  outputName: "quickhack-code-structure",
  kicker: "REPOSITORY-GROUNDED CALL PATH",
  titleLead: "버튼 한 번이 지나가는,",
  titleStrong: "실제 코드 레이어와 트랜잭션 경로",
  summary: [
    "매입 확정 요청을 대표 경로로 추적해",
    "클라이언트·API·정책·원장·관측 경계를 한 장에 담았습니다.",
  ],
  tech: [
    "quickhack_client",
    "app/api",
    "quickhack_server",
    "quickhack_shared",
    "Prisma Transaction",
  ],
  ariaLabel: "QuickHack 실제 코드 레이어 호출 구조",
  lanes: [
    {
      left: 30,
      width: 500,
      index: "01",
      title: "PRESENTATION & ROUTING",
      subtitle: "UI 요청 · Next.js route · client runtime proxy",
    },
    {
      left: 590,
      width: 500,
      index: "02",
      title: "SERVER BOUNDARY",
      subtitle: "세션 · 역할 · 민감 작업 OTP · operation trace",
    },
    {
      left: 1150,
      width: 350,
      index: "03",
      title: "DOMAIN TRANSACTION",
      subtitle: "서비스 · 상태 정책 · 수량 원장",
    },
    {
      left: 1540,
      width: 240,
      index: "04",
      title: "PERSISTENCE",
      subtitle: "Prisma client · SQLite models",
    },
  ],
  nodes: [
    node({
      id: "purchase-ui",
      x: 40,
      y: 155,
      eyebrow: "quickhack_client/components",
      title: "PurchasePendingListView",
      description: "매입 확정 스냅샷과 OTP 입력",
      detail: "purchase-pending-list-view.tsx",
      tone: "local",
      icon: "component",
      width: 240,
    }),
    node({
      id: "route-wrapper",
      x: 330,
      y: 155,
      eyebrow: "app/api/inbound/purchase-confirm",
      title: "Next.js Route Wrapper",
      description: "서버 POST 구현을 그대로 export",
      detail: "route.ts → { POST }",
      tone: "local",
      icon: "route",
      width: 240,
    }),
    node({
      id: "runtime-proxy",
      x: 330,
      y: 445,
      eyebrow: "CLIENT RUNTIME BRANCH",
      title: "proxyToServer",
      description: "DB 없는 배포본에서 중앙 서버로 전달",
      detail: "isClientRuntime() · HTTPS proxy",
      tone: "local",
      icon: "route",
      width: 240,
    }),
    node({
      id: "post-handler",
      x: 620,
      y: 155,
      eyebrow: "quickhack_server/api/inbound",
      title: "POST(request)",
      description: "body 파싱과 operation trace 시작",
      detail: "purchase-confirm.ts",
      tone: "core",
      icon: "function",
      width: 240,
    }),
    node({
      id: "auth-guard",
      x: 620,
      y: 445,
      eyebrow: "AUTHORIZATION BOUNDARY",
      title: "Session · Role · OTP",
      description: "MANAGER 권한과 민감 작업 인증 확인",
      detail: "SENSITIVE_ACTIONS.inboundPurchaseConfirm",
      tone: "core",
      icon: "auth",
      width: 240,
    }),
    node({
      id: "confirm-service",
      x: 910,
      y: 155,
      eyebrow: "quickhack_server/inbound",
      title: "confirmInboundPurchases",
      description: "대상 검증 · 확정 · 활동 로그 기록",
      detail: "purchase-confirm-service.ts",
      tone: "core",
      icon: "function",
      width: 240,
    }),
    node({
      id: "transition-policy",
      x: 910,
      y: 445,
      eyebrow: "quickhack_shared/inventory",
      title: "Transition Policy",
      description: "허용된 재고 상태 전이만 통과",
      detail: "assertInventoryStatusTransition",
      tone: "reliability",
      icon: "policy",
      width: 240,
    }),
    node({
      id: "measured-tx",
      x: 1200,
      y: 155,
      eyebrow: "TRANSACTION BOUNDARY",
      title: "runMeasuredTransaction",
      description: "매입 확정 변경을 단일 트랜잭션으로 실행",
      detail: "operation: inbound.purchase.confirm",
      tone: "reliability",
      icon: "transaction",
      width: 250,
    }),
    node({
      id: "quantity-ledger",
      x: 1200,
      y: 445,
      eyebrow: "quickhack_server/inventory",
      title: "Quantity Ledger",
      description: "상태별 잔액과 append-only 이동 이력",
      detail: "transitionInventoryStatusWithLedger",
      tone: "reliability",
      icon: "ledger",
      width: 250,
    }),
    node({
      id: "trace",
      x: 1200,
      y: 665,
      eyebrow: "OBSERVABILITY",
      title: "Operation · Transaction Trace",
      description: "SERVICE_WRITE와 DB 구간 시간을 측정",
      detail: "operation-trace.ts · transaction-trace.ts",
      tone: "warning",
      icon: "observability",
      width: 250,
    }),
    node({
      id: "prisma-client",
      x: 1530,
      y: 155,
      eyebrow: "quickhack_server/core",
      title: "Prisma Client",
      description: "서버 런타임의 중앙 데이터 접근점",
      detail: "core/prisma.ts",
      tone: "reliability",
      icon: "database",
      width: 240,
    }),
    node({
      id: "prisma-models",
      x: 1530,
      y: 445,
      eyebrow: "prisma/schema.prisma",
      title: "SQLite Domain Models",
      description: "devices · inbounds · inventory · ledger",
      detail: "balances + movements + activity_logs",
      tone: "reliability",
      icon: "table",
      width: 240,
    }),
  ],
  edges: [
    link("code-ui-route", "purchase-ui", "route-wrapper", {
      label: "POST + items snapshot",
      style: requestStyle,
    }),
    link("code-route-handler", "route-wrapper", "post-handler", {
      label: "server export",
      style: requestStyle,
    }),
    link("code-route-proxy", "route-wrapper", "runtime-proxy", {
      sourceHandle: "bottom-source",
      targetHandle: "top-target",
      label: "client runtime",
      style: backgroundStyle,
    }),
    link("code-proxy-handler", "runtime-proxy", "post-handler", {
      label: "central server",
      style: backgroundStyle,
    }),
    link("code-handler-auth", "post-handler", "auth-guard", {
      sourceHandle: "bottom-source",
      targetHandle: "top-target",
      label: "authorize",
      style: processingStyle,
    }),
    link("code-auth-service", "auth-guard", "confirm-service", {
      label: "verified user",
      style: processingStyle,
    }),
    link("code-service-policy", "confirm-service", "transition-policy", {
      sourceHandle: "bottom-source",
      targetHandle: "top-target",
      label: "assert transition",
      style: reliableStyle,
    }),
    link("code-service-tx", "confirm-service", "measured-tx", {
      label: "single commit unit",
      style: processingStyle,
    }),
    link("code-tx-ledger", "measured-tx", "quantity-ledger", {
      sourceHandle: "bottom-source",
      targetHandle: "top-target",
      label: "tx client",
      style: reliableStyle,
    }),
    link("code-policy-ledger", "transition-policy", "quantity-ledger", {
      label: "allowed status",
      style: reliableStyle,
    }),
    link("code-ledger-prisma", "quantity-ledger", "prisma-models", {
      label: "balance + movement",
      style: reliableStyle,
    }),
    link("code-tx-prisma", "measured-tx", "prisma-client", {
      label: "Prisma $transaction",
      style: reliableStyle,
    }),
    link("code-prisma-model", "prisma-client", "prisma-models", {
      sourceHandle: "bottom-source",
      targetHandle: "top-target",
      style: reliableStyle,
    }),
    link("code-handler-trace", "post-handler", "trace", {
      sourceHandle: "bottom-source",
      targetHandle: "left-target",
      style: backgroundStyle,
    }),
    link("code-tx-trace", "measured-tx", "trace", {
      sourceHandle: "bottom-source",
      targetHandle: "top-target",
      label: "timing",
      style: backgroundStyle,
    }),
  ],
  legend: [
    { label: "동기 요청과 함수 호출", tone: "solid" },
    { label: "정책·트랜잭션·원장 경계", tone: "dashed" },
    { label: "실행 추적과 배포 분기", tone: "muted" },
  ],
};

const businessDataFlowDiagram: ArchitectureDiagram = {
  id: "business-data-flow",
  outputName: "quickhack-business-data-flow",
  kicker: "END-TO-END BUSINESS DATA FLOW",
  titleLead: "입고된 한 대가,",
  titleStrong: "판매와 반품까지 이어지는 데이터 흐름",
  summary: [
    "PG 번호를 실물 식별 축으로 삼아",
    "입고·검수·재고·주문 매칭·배송·매출의 증거를 연결합니다.",
  ],
  tech: [
    "PG Identity",
    "Inventory Ledger",
    "Coupang Raw Sync",
    "Package Group",
    "Sales Record",
  ],
  ariaLabel: "QuickHack 핵심 업무 데이터 흐름",
  lanes: [
    {
      left: 30,
      width: 500,
      index: "01",
      title: "INBOUND EVIDENCE",
      subtitle: "입고 차수 · 실물 식별 · 검수",
    },
    {
      left: 590,
      width: 500,
      index: "02",
      title: "INVENTORY CONTROL",
      subtitle: "매입 확정 · 현재 상태 · 수량 원장",
    },
    {
      left: 1150,
      width: 350,
      index: "03",
      title: "FULFILLMENT",
      subtitle: "주문 매칭 · 포장 그룹 · 배송",
    },
    {
      left: 1540,
      width: 240,
      index: "04",
      title: "OUTCOME",
      subtitle: "매출 확정 · 반품 재검수",
    },
  ],
  nodes: [
    node({
      id: "inbound-batch",
      x: 30,
      y: 145,
      eyebrow: "INBOUND PLAN",
      title: "inbound_batches",
      description: "업무일자·차수·예정 수량",
      detail: "batch_date + batch_no",
      tone: "local",
      icon: "snapshot",
      width: 220,
    }),
    node({
      id: "device-inbound",
      x: 295,
      y: 145,
      eyebrow: "PHYSICAL IDENTITY",
      title: "devices + inbounds",
      description: "PG · IMEI와 매입 증거 연결",
      detail: "pg_no = lifecycle key",
      tone: "local",
      icon: "device",
      width: 220,
    }),
    node({
      id: "inspection",
      x: 560,
      y: 145,
      eyebrow: "QUALITY EVIDENCE",
      title: "inspections",
      description: "외관·기능 검수 이력 누적",
      detail: "inspection_type · result",
      tone: "local",
      icon: "component",
      width: 220,
    }),
    node({
      id: "purchase-confirm",
      x: 825,
      y: 145,
      eyebrow: "DOMAIN COMMAND",
      title: "매입 확정",
      description: "검증된 대상과 매입가를 확정",
      detail: "confirmInboundPurchases",
      tone: "core",
      icon: "function",
      width: 220,
    }),
    node({
      id: "inventory-state",
      x: 1090,
      y: 145,
      eyebrow: "DEVICE STATE",
      title: "inventory",
      description: "PG별 현재 재고 상태와 위치",
      detail: "inventory_status · location",
      tone: "reliability",
      icon: "database",
      width: 220,
    }),
    node({
      id: "inventory-ledger",
      x: 1355,
      y: 145,
      eyebrow: "QUANTITY EVIDENCE",
      title: "balances + movements",
      description: "SKU·상태별 잔액과 불변 이동 이력",
      detail: "idempotency_key · before/after",
      tone: "reliability",
      icon: "ledger",
      width: 220,
    }),
    node({
      id: "coupang-order",
      x: 30,
      y: 430,
      eyebrow: "CHANNEL READ MODEL",
      title: "coupang_order_raw",
      description: "주문·배송 단위 원문 동기화",
      detail: "external_order_id + shipment_id",
      tone: "external",
      icon: "coupang",
      width: 220,
    }),
    node({
      id: "order-matcher",
      x: 295,
      y: 430,
      eyebrow: "MATCHING SERVICE",
      title: "matchOrderInventory",
      description: "판매 조건과 가용 재고를 대조",
      detail: "order-inventory-matching-service.ts",
      tone: "core",
      icon: "function",
      width: 220,
    }),
    node({
      id: "allocation",
      x: 560,
      y: 430,
      eyebrow: "PG RESERVATION",
      title: "match_worker_allocation",
      description: "외부 주문 라인과 실제 PG 연결",
      detail: "allocation_status · pg_no",
      tone: "core",
      icon: "snapshot",
      width: 220,
    }),
    node({
      id: "package-group",
      x: 825,
      y: 430,
      eyebrow: "PHYSICAL PARCEL",
      title: "shipment_package_groups",
      description: "같이 포장할 allocation을 동결",
      detail: "DRAFT → FROZEN",
      tone: "core",
      icon: "domain",
      width: 220,
    }),
    node({
      id: "carrier-shipment",
      x: 1090,
      y: 430,
      eyebrow: "CARRIER EVIDENCE",
      title: "carrier_shipments",
      description: "송장 발급과 배송 추적 상태",
      detail: "tracking_number · revision_no",
      tone: "external",
      icon: "carrier",
      width: 220,
    }),
    node({
      id: "sales-record",
      x: 1355,
      y: 430,
      eyebrow: "CONFIRMED OUTCOME",
      title: "sales_records",
      description: "배송 증거로 확정한 PG별 매출 원장",
      detail: "allocation_id · sold_at",
      tone: "success",
      icon: "success",
      width: 220,
    }),
    node({
      id: "return-raw",
      x: 825,
      y: 665,
      eyebrow: "RETURN READ MODEL",
      title: "coupang_return_raw",
      description: "반품·취소 접수 원문",
      detail: "external_receipt_id",
      tone: "external",
      icon: "return",
      width: 220,
    }),
    node({
      id: "return-allocation",
      x: 1090,
      y: 665,
      eyebrow: "RETURN LINK",
      title: "return allocation",
      description: "반품 접수와 출고 PG를 연결",
      detail: "coupang_return_allocation",
      tone: "warning",
      icon: "snapshot",
      width: 220,
    }),
    node({
      id: "return-inspection",
      x: 1355,
      y: 665,
      eyebrow: "RE-ENTRY CONTROL",
      title: "반품 재검수 → 재고",
      description: "검수 결과에 따라 상태를 재분류",
      detail: "finalizePersistedCoupangReturnWrite",
      tone: "warning",
      icon: "return",
      width: 220,
    }),
  ],
  edges: [
    link("biz-batch-device", "inbound-batch", "device-inbound", {
      label: "1:N",
      style: requestStyle,
    }),
    link("biz-device-inspection", "device-inbound", "inspection", {
      label: "PG",
      style: requestStyle,
    }),
    link("biz-inspection-confirm", "inspection", "purchase-confirm", {
      label: "검수 완료",
      style: processingStyle,
    }),
    link("biz-confirm-inventory", "purchase-confirm", "inventory-state", {
      label: "상태 전이",
      style: reliableStyle,
    }),
    link("biz-inventory-ledger", "inventory-state", "inventory-ledger", {
      label: "IN / OUT movement",
      style: reliableStyle,
    }),
    link("biz-order-matcher", "coupang-order", "order-matcher", {
      label: "동기화 주문",
      style: externalStyle,
    }),
    link("biz-ledger-matcher", "inventory-ledger", "order-matcher", {
      sourceHandle: "bottom-source",
      targetHandle: "top-target",
      label: "가용 수량",
      style: backgroundStyle,
    }),
    link("biz-matcher-allocation", "order-matcher", "allocation", {
      label: "PG 배정",
      style: processingStyle,
    }),
    link("biz-allocation-package", "allocation", "package-group", {
      label: "member",
      style: processingStyle,
    }),
    link("biz-package-carrier", "package-group", "carrier-shipment", {
      label: "송장 발급",
      style: externalStyle,
    }),
    link("biz-carrier-sales", "carrier-shipment", "sales-record", {
      label: "배송 확정",
      style: successStyle,
    }),
    link("biz-order-return", "coupang-order", "return-raw", {
      sourceHandle: "bottom-source",
      targetHandle: "left-target",
      style: externalStyle,
    }),
    link("biz-return-allocation", "return-raw", "return-allocation", {
      label: "allocation_id",
      style: externalStyle,
    }),
    link("biz-return-inspection", "return-allocation", "return-inspection", {
      label: "검수 대상 PG",
      style: dangerStyle,
    }),
    link("biz-return-inventory", "return-inspection", "inventory-state", {
      sourceHandle: "top-source",
      targetHandle: "bottom-target",
      label: "재고 재분류",
      style: dangerStyle,
    }),
  ],
  legend: [
    { label: "실물 PG의 정상 처리 흐름", tone: "solid" },
    { label: "원문 동기화와 수량 증거", tone: "dashed" },
    { label: "반품 재진입과 재검수", tone: "danger" },
  ],
};

const safeExternalWriteDiagram: ArchitectureDiagram = {
  id: "safe-external-write",
  outputName: "quickhack-safe-external-write",
  kicker: "FAILURE-AWARE EXTERNAL WRITE",
  titleLead: "외부 API 쓰기를,",
  titleStrong: "재전송보다 검증 가능한 상태 기계로",
  summary: [
    "멱등 키·대상 스냅샷·쓰기 시도·GET 재검증을 분리해",
    "응답이 애매한 순간에도 중복 처리 대신 복구 경로를 남깁니다.",
  ],
  tech: [
    "Idempotency Key",
    "Immutable Target Snapshot",
    "WRITE / VERIFY_READ",
    "QHKEY",
    "Manual Review",
  ],
  ariaLabel: "QuickHack 안전한 외부 쓰기 상태 흐름",
  lanes: [
    {
      left: 30,
      width: 500,
      index: "01",
      title: "REQUEST SAFETY",
      subtitle: "멱등 요청 생성 · 대상 스냅샷",
    },
    {
      left: 590,
      width: 500,
      index: "02",
      title: "SIGNED WRITE",
      subtitle: "제어 상태 확인 · QHKEY · adapter",
    },
    {
      left: 1150,
      width: 350,
      index: "03",
      title: "EXTERNAL VERIFICATION",
      subtitle: "Coupang 응답 · targeted GET",
    },
    {
      left: 1540,
      width: 240,
      index: "04",
      title: "LOCAL FINALIZATION",
      subtitle: "로컬 확정 · 완료 또는 검토",
    },
  ],
  nodes: [
    node({
      id: "write-command",
      x: 40,
      y: 150,
      eyebrow: "DOMAIN INTENT",
      title: "Write Command",
      description: "주문·송장·반품 변경 의도",
      detail: "SalesChannelWriteCommand",
      tone: "core",
      icon: "function",
      width: 230,
    }),
    node({
      id: "write-request",
      x: 325,
      y: 150,
      eyebrow: "PERSISTED REQUEST",
      title: "PENDING",
      description: "멱등 키로 기존 요청을 먼저 탐색",
      detail: "createWriteRequest",
      tone: "reliability",
      icon: "database",
      width: 230,
    }),
    node({
      id: "write-safety",
      x: 610,
      y: 150,
      eyebrow: "SAFETY GATES",
      title: "Control + Snapshot",
      description: "채널 제어 상태와 허용 endpoint 확인",
      detail: "assertControlIsOpen · targets[]",
      tone: "reliability",
      icon: "gateway",
      width: 230,
    }),
    node({
      id: "write-attempt",
      x: 895,
      y: 150,
      eyebrow: "ATTEMPT: WRITE",
      title: "SENDING",
      description: "QHKEY credential context에서 실행",
      detail: "executeSalesChannelWriteAdapter",
      tone: "core",
      icon: "auth",
      width: 230,
    }),
    node({
      id: "coupang-write-api",
      x: 1180,
      y: 150,
      eyebrow: "EXTERNAL SYSTEM",
      title: "Coupang Write API",
      description: "주문 상태·송장·반품 endpoint",
      detail: "PATCH / POST",
      tone: "external",
      icon: "coupang",
      width: 230,
    }),
    node({
      id: "verify-read",
      x: 1465,
      y: 150,
      eyebrow: "ATTEMPT: VERIFY_READ",
      title: "VERIFYING",
      description: "targeted GET로 외부 반영 여부 확인",
      detail: "CONFIRMED · NOT_APPLIED · UNKNOWN",
      tone: "warning",
      icon: "snapshot",
      width: 250,
    }),
    node({
      id: "ambiguous",
      x: 895,
      y: 430,
      eyebrow: "WRITE FAILURE",
      title: "FAILED / AMBIGUOUS",
      description: "전송 결과를 단정할 수 없는 실패",
      detail: "자동 재전송 금지",
      tone: "danger",
      icon: "warning",
      width: 230,
    }),
    node({
      id: "not-applied",
      x: 1180,
      y: 430,
      eyebrow: "VERIFICATION BRANCH",
      title: "NOT_APPLIED / UNKNOWN",
      description: "미반영은 재시도, 불명확은 검토",
      detail: "verification result",
      tone: "warning",
      icon: "retry",
      width: 230,
    }),
    node({
      id: "local-pending",
      x: 1465,
      y: 430,
      eyebrow: "VERIFICATION RESULT",
      title: "LOCAL_PENDING",
      description: "외부 반영 확인, 내부 확정 대기",
      detail: "attempt: LOCAL_FINALIZE",
      tone: "reliability",
      icon: "transaction",
      width: 250,
    }),
    node({
      id: "manual-review",
      x: 895,
      y: 665,
      eyebrow: "OPERATOR RECOVERY",
      title: "Recheck · Manual Decision",
      description: "재조회·수동 판정·로컬 확정 재시도",
      detail: "sales-channel-write-review-service.ts",
      tone: "warning",
      icon: "operator",
      width: 250,
    }),
    node({
      id: "review-required",
      x: 1180,
      y: 665,
      eyebrow: "SAFE STOP",
      title: "REVIEW_REQUIRED",
      description: "UNKNOWN 또는 로컬 확정 실패",
      detail: "failure_stage + error evidence",
      tone: "danger",
      icon: "warning",
      width: 230,
    }),
    node({
      id: "write-completed",
      x: 1465,
      y: 665,
      eyebrow: "FINAL STATE",
      title: "COMPLETED",
      description: "외부 반영과 로컬 도메인 확정 완료",
      detail: "local_finalized_at",
      tone: "success",
      icon: "success",
      width: 250,
    }),
  ],
  edges: [
    link("write-command-request", "write-command", "write-request", {
      label: "idempotency_key",
      style: requestStyle,
    }),
    link("write-request-safety", "write-request", "write-safety", {
      label: "immutable targets",
      style: reliableStyle,
    }),
    link("write-safety-attempt", "write-safety", "write-attempt", {
      label: "allowed",
      style: processingStyle,
    }),
    link("write-attempt-coupang", "write-attempt", "coupang-write-api", {
      label: "signed WRITE",
      style: externalStyle,
    }),
    link("write-coupang-verify", "coupang-write-api", "verify-read", {
      label: "response + GET evidence",
      style: externalStyle,
    }),
    link("write-verify-local", "verify-read", "local-pending", {
      sourceHandle: "bottom-source",
      targetHandle: "top-target",
      label: "CONFIRMED",
      style: successStyle,
    }),
    link("write-local-complete", "local-pending", "write-completed", {
      sourceHandle: "bottom-source",
      targetHandle: "top-target",
      label: "transaction success",
      style: successStyle,
    }),
    link("write-attempt-ambiguous", "write-attempt", "ambiguous", {
      sourceHandle: "bottom-source",
      targetHandle: "top-target",
      label: "transport / response",
      style: dangerStyle,
    }),
    link("write-verify-not-applied", "verify-read", "not-applied", {
      sourceHandle: "bottom-source",
      targetHandle: "right-target",
      label: "not confirmed",
      style: dangerStyle,
    }),
    link("write-ambiguous-review", "ambiguous", "review-required", {
      sourceHandle: "bottom-source",
      targetHandle: "left-target",
      label: "no blind resend",
      style: dangerStyle,
    }),
    link("write-not-applied-manual", "not-applied", "manual-review", {
      sourceHandle: "bottom-source",
      targetHandle: "top-target",
      label: "safe retry",
      style: backgroundStyle,
    }),
    link("write-unknown-review", "not-applied", "review-required", {
      sourceHandle: "bottom-source",
      targetHandle: "top-target",
      label: "UNKNOWN",
      style: dangerStyle,
    }),
    link("write-review-manual", "review-required", "manual-review", {
      sourceHandle: "left-source",
      targetHandle: "right-target",
      label: "operator action",
      style: backgroundStyle,
    }),
    link("write-manual-local", "manual-review", "local-pending", {
      sourceHandle: "right-source",
      targetHandle: "left-target",
      label: "local finalize retry",
      style: backgroundStyle,
    }),
  ],
  legend: [
    { label: "정상 쓰기·검증·로컬 확정", tone: "solid" },
    { label: "증거 기반 재조회·운영 복구", tone: "dashed" },
    { label: "애매한 결과에서 안전 정지", tone: "danger" },
  ],
};

const workerRecoveryDiagram: ArchitectureDiagram = {
  id: "worker-recovery",
  outputName: "quickhack-worker-recovery",
  kicker: "LEASE-BASED BACKGROUND EXECUTION",
  titleLead: "백그라운드 작업을,",
  titleStrong: "스케줄·임대·진행률·재시도로 운영",
  summary: [
    "DB에 등록된 작업 상태를 기준으로 due job을 선점하고",
    "heartbeat와 실행 로그를 남겨 중단 이후에도 복구할 수 있습니다.",
  ],
  tech: [
    "Worker Manager",
    "DB Lease",
    "AbortSignal",
    "Heartbeat",
    "Retry Waiting",
  ],
  ariaLabel: "QuickHack Worker 실행과 실패 복구 구조",
  lanes: [
    {
      left: 30,
      width: 500,
      index: "01",
      title: "MANAGER LOOP",
      subtitle: "등록 보장 · interval tick · 중단 복구",
    },
    {
      left: 590,
      width: 500,
      index: "02",
      title: "DUE JOB SELECTION",
      subtitle: "next_run_at · 최대 10개 · 순차 실행",
    },
    {
      left: 1150,
      width: 350,
      index: "03",
      title: "LEASED EXECUTION",
      subtitle: "atomic lock · heartbeat · progress",
    },
    {
      left: 1540,
      width: 240,
      index: "04",
      title: "RESULT & RECOVERY",
      subtitle: "SUCCESS · RETRY_WAITING · FAILED",
    },
  ],
  nodes: [
    node({
      id: "worker-manager",
      x: 35,
      y: 150,
      eyebrow: "quickhack_server/workers",
      title: "startWorkerManager",
      description: "서버 런타임에서 interval tick 시작",
      detail: "manager.ts",
      tone: "core",
      icon: "worker",
      width: 225,
    }),
    node({
      id: "worker-schedule",
      x: 315,
      y: 150,
      eyebrow: "SCHEDULE POLICY",
      title: "Next Run Policy",
      description: "interval · daily KST · manual",
      detail: "nextRegisteredWorkerRunAt",
      tone: "core",
      icon: "timer",
      width: 225,
    }),
    node({
      id: "due-jobs",
      x: 595,
      y: 150,
      eyebrow: "PERSISTED QUEUE",
      title: "runDueWorkerJobs",
      description: "활성화되고 시간이 된 작업 조회",
      detail: "next_run_at ASC · take 10",
      tone: "reliability",
      icon: "database",
      width: 225,
    }),
    node({
      id: "acquire-lease",
      x: 875,
      y: 150,
      eyebrow: "ATOMIC CLAIM",
      title: "Acquire DB Lease",
      description: "locked_by · locked_until 조건부 갱신",
      detail: "runWorkerJob",
      tone: "reliability",
      icon: "lock",
      width: 225,
    }),
    node({
      id: "registered-worker",
      x: 1155,
      y: 150,
      eyebrow: "WORKER REGISTRY",
      title: "findRegisteredWorker",
      description: "키별 실행 함수와 시도 정책 선택",
      detail: "registry.ts · maxAttempts",
      tone: "core",
      icon: "function",
      width: 225,
    }),
    node({
      id: "worker-domain",
      x: 1435,
      y: 150,
      eyebrow: "DOMAIN / INTEGRATION",
      title: "worker.run(context)",
      description: "Coupang·Logen·백업·감사·통계",
      detail: "AbortSignal + lease guard",
      tone: "external",
      icon: "function",
      width: 260,
    }),
    node({
      id: "sync-recovery",
      x: 35,
      y: 440,
      eyebrow: "MANAGER TICK BRANCH",
      title: "Recover Interrupted Sync",
      description: "중단된 Coupang read sync를 주기 복구",
      detail: "every 60 seconds",
      tone: "warning",
      icon: "retry",
      width: 225,
    }),
    node({
      id: "ensure-jobs",
      x: 315,
      y: 440,
      eyebrow: "BOOTSTRAP",
      title: "Ensure Registered Jobs",
      description: "registry 항목을 DB job으로 upsert",
      detail: "ensureRegisteredWorkerJobs",
      tone: "reliability",
      icon: "table",
      width: 225,
    }),
    node({
      id: "heartbeat",
      x: 595,
      y: 440,
      eyebrow: "LEASE HEALTH",
      title: "Heartbeat + Progress",
      description: "임대 연장과 current / total 저장",
      detail: "assertLeaseActive · updateProgress",
      tone: "reliability",
      icon: "observability",
      width: 225,
    }),
    node({
      id: "worker-success",
      x: 875,
      y: 440,
      eyebrow: "TERMINAL STATE",
      title: "SUCCESS",
      description: "다음 실행 시각 계산 후 lock 해제",
      detail: "last_finished_at · summary",
      tone: "success",
      icon: "success",
      width: 225,
    }),
    node({
      id: "worker-retry",
      x: 1155,
      y: 440,
      eyebrow: "RECOVERABLE FAILURE",
      title: "RETRY_WAITING",
      description: "최대 시도 전이면 다음 재시도 예약",
      detail: "default retry: 60 sec",
      tone: "warning",
      icon: "retry",
      width: 225,
    }),
    node({
      id: "worker-failed",
      x: 1435,
      y: 440,
      eyebrow: "TERMINAL FAILURE",
      title: "FAILED",
      description: "시도 한도 초과 후 증거 보존",
      detail: "error_code · error_message",
      tone: "danger",
      icon: "warning",
      width: 260,
    }),
    node({
      id: "worker-logs",
      x: 875,
      y: 650,
      eyebrow: "OPERATING EVIDENCE",
      title: "server_job_logs",
      description: "성공·실패 실행 결과와 필드 기록",
      detail: "trace_id · duration · summary",
      tone: "warning",
      icon: "observability",
      width: 260,
    }),
  ],
  edges: [
    link("worker-manager-schedule", "worker-manager", "worker-schedule", {
      label: "tick",
      style: requestStyle,
    }),
    link("worker-schedule-due", "worker-schedule", "due-jobs", {
      label: "next_run_at",
      style: processingStyle,
    }),
    link("worker-due-lease", "due-jobs", "acquire-lease", {
      label: "due jobs",
      style: reliableStyle,
    }),
    link("worker-lease-registry", "acquire-lease", "registered-worker", {
      label: "lease acquired",
      style: reliableStyle,
    }),
    link("worker-registry-domain", "registered-worker", "worker-domain", {
      label: "run(context)",
      style: processingStyle,
    }),
    link("worker-manager-recovery", "worker-manager", "sync-recovery", {
      sourceHandle: "bottom-source",
      targetHandle: "top-target",
      style: backgroundStyle,
    }),
    link("worker-manager-ensure", "worker-manager", "ensure-jobs", {
      sourceHandle: "right-source",
      targetHandle: "top-target",
      label: "startup",
      style: backgroundStyle,
    }),
    link("worker-lease-heartbeat", "acquire-lease", "heartbeat", {
      sourceHandle: "bottom-source",
      targetHandle: "top-target",
      label: "extend lease",
      style: backgroundStyle,
    }),
    link("worker-domain-success", "worker-domain", "worker-success", {
      sourceHandle: "bottom-source",
      targetHandle: "right-target",
      label: "resolved",
      style: successStyle,
    }),
    link("worker-domain-retry", "worker-domain", "worker-retry", {
      sourceHandle: "bottom-source",
      targetHandle: "right-target",
      label: "retryable",
      style: dangerStyle,
    }),
    link("worker-domain-failed", "worker-domain", "worker-failed", {
      sourceHandle: "bottom-source",
      targetHandle: "top-target",
      label: "attempt limit",
      style: dangerStyle,
    }),
    link("worker-success-logs", "worker-success", "worker-logs", {
      sourceHandle: "bottom-source",
      targetHandle: "top-target",
      style: backgroundStyle,
    }),
    link("worker-retry-logs", "worker-retry", "worker-logs", {
      sourceHandle: "bottom-source",
      targetHandle: "right-target",
      style: backgroundStyle,
    }),
    link("worker-failed-logs", "worker-failed", "worker-logs", {
      sourceHandle: "bottom-source",
      targetHandle: "right-target",
      style: backgroundStyle,
    }),
  ],
  legend: [
    { label: "스케줄부터 임대 실행까지", tone: "solid" },
    { label: "heartbeat·등록·중단 복구", tone: "dashed" },
    { label: "재시도 또는 최종 실패", tone: "danger" },
  ],
};

const coreDataModelDiagram: ArchitectureDiagram = {
  id: "core-data-model",
  outputName: "quickhack-core-data-model",
  kicker: "CORE PRISMA RELATIONSHIP MAP",
  titleLead: "PG 실물을 중심으로,",
  titleStrong: "재고·주문·배송·외부 쓰기 증거를 연결",
  summary: [
    "전체 스키마 중 핵심 운영 흐름의 관계만 추려",
    "현재 상태 테이블과 불변 이력 테이블의 역할 차이를 보여줍니다.",
  ],
  tech: [
    "Prisma Schema",
    "SQLite",
    "PG Foreign Key",
    "Append-only Ledger",
    "Immutable Attempts",
  ],
  ariaLabel: "QuickHack 핵심 Prisma 데이터 모델 관계",
  lanes: [
    {
      left: 30,
      width: 500,
      index: "01",
      title: "PHYSICAL MASTER",
      subtitle: "실물 PG · 입고 · 검수 · 현재 상태",
    },
    {
      left: 590,
      width: 500,
      index: "02",
      title: "INVENTORY LEDGER",
      subtitle: "정규화 SKU · 상태별 잔액 · 이동 이력",
    },
    {
      left: 1150,
      width: 350,
      index: "03",
      title: "ORDER & SHIPMENT",
      subtitle: "채널 원문 · PG 배정 · 포장 · 배송",
    },
    {
      left: 1540,
      width: 240,
      index: "04",
      title: "WRITE EVIDENCE",
      subtitle: "요청 · 대상 스냅샷 · 시도",
    },
  ],
  nodes: [
    node({
      id: "m-devices",
      x: 25,
      y: 145,
      eyebrow: "MASTER · 1 ROW / PG",
      title: "devices",
      description: "PK device_id · UQ pg_no",
      detail: "IMEI · ADB serial · SKU FK",
      tone: "local",
      icon: "table",
      width: 195,
    }),
    node({
      id: "m-inbounds",
      x: 25,
      y: 390,
      eyebrow: "PURCHASE EVIDENCE",
      title: "inbounds",
      description: "N:1 devices(pg_no)",
      detail: "batch · price · status",
      tone: "local",
      icon: "table",
      width: 195,
    }),
    node({
      id: "m-inspections",
      x: 25,
      y: 635,
      eyebrow: "QUALITY HISTORY",
      title: "inspections",
      description: "N:1 devices · optional inbound",
      detail: "type · round · result",
      tone: "local",
      icon: "table",
      width: 195,
    }),
    node({
      id: "m-inventory",
      x: 270,
      y: 145,
      eyebrow: "CURRENT PROJECTION",
      title: "inventory",
      description: "1:1 devices(pg_no)",
      detail: "status · location",
      tone: "reliability",
      icon: "table",
      width: 195,
    }),
    node({
      id: "m-skus",
      x: 515,
      y: 145,
      eyebrow: "NORMALIZED SKU",
      title: "inventory_skus",
      description: "UQ 4 product dimensions",
      detail: "model · storage · color · grade",
      tone: "reliability",
      icon: "table",
      width: 195,
    }),
    node({
      id: "m-balances",
      x: 515,
      y: 390,
      eyebrow: "CURRENT QUANTITY",
      title: "quantity_balances",
      description: "UQ sku_id + status",
      detail: "quantity · version",
      tone: "reliability",
      icon: "database",
      width: 195,
    }),
    node({
      id: "m-movements",
      x: 515,
      y: 635,
      eyebrow: "APPEND-ONLY LEDGER",
      title: "quantity_movements",
      description: "N:1 balance",
      detail: "idempotency · before/after",
      tone: "reliability",
      icon: "ledger",
      width: 195,
    }),
    node({
      id: "m-orders",
      x: 760,
      y: 145,
      eyebrow: "CHANNEL READ MODEL",
      title: "coupang_order_raw",
      description: "UQ order_id + shipment_id",
      detail: "raw sync projection",
      tone: "external",
      icon: "table",
      width: 195,
    }),
    node({
      id: "m-allocation",
      x: 760,
      y: 390,
      eyebrow: "ORDER ↔ PHYSICAL PG",
      title: "match_allocation",
      description: "N:1 order · device · SKU",
      detail: "allocation_status",
      tone: "core",
      icon: "table",
      width: 195,
    }),
    node({
      id: "m-returns",
      x: 760,
      y: 635,
      eyebrow: "RETURN READ MODEL",
      title: "coupang_return_raw",
      description: "optional N:1 order",
      detail: "UQ external_receipt_id",
      tone: "external",
      icon: "table",
      width: 195,
    }),
    node({
      id: "m-groups",
      x: 1005,
      y: 145,
      eyebrow: "PHYSICAL PARCEL",
      title: "package_groups",
      description: "grouping snapshot + status",
      detail: "current carrier FK",
      tone: "core",
      icon: "table",
      width: 195,
    }),
    node({
      id: "m-members",
      x: 1005,
      y: 390,
      eyebrow: "IMMUTABLE MEMBERSHIP",
      title: "package_members",
      description: "N:1 group · allocation",
      detail: "added_at · removed_at",
      tone: "core",
      icon: "snapshot",
      width: 195,
    }),
    node({
      id: "m-return-allocation",
      x: 1005,
      y: 635,
      eyebrow: "RETURN ↔ PG",
      title: "return_allocation",
      description: "N:1 return · allocation",
      detail: "external receipt + pg_no",
      tone: "warning",
      icon: "table",
      width: 195,
    }),
    node({
      id: "m-carrier",
      x: 1250,
      y: 145,
      eyebrow: "CARRIER RESULT",
      title: "carrier_shipments",
      description: "N:1 package group",
      detail: "tracking · revision",
      tone: "external",
      icon: "table",
      width: 195,
    }),
    node({
      id: "m-sales",
      x: 1250,
      y: 390,
      eyebrow: "CONFIRMED SALES LEDGER",
      title: "sales_records",
      description: "1:1 allocation",
      detail: "device · SKU · inbound FK",
      tone: "success",
      icon: "table",
      width: 195,
    }),
    node({
      id: "m-write-request",
      x: 1495,
      y: 145,
      eyebrow: "WRITE STATE MACHINE",
      title: "write_requests",
      description: "UQ idempotency_key",
      detail: "status · failure_stage",
      tone: "warning",
      icon: "table",
      width: 230,
    }),
    node({
      id: "m-write-target",
      x: 1460,
      y: 430,
      eyebrow: "IMMUTABLE TARGET",
      title: "write_targets",
      description: "N:1 request",
      detail: "PG · allocation · package snapshot",
      tone: "warning",
      icon: "snapshot",
      width: 170,
    }),
    node({
      id: "m-write-attempt",
      x: 1640,
      y: 430,
      eyebrow: "APPEND-ONLY ATTEMPT",
      title: "write_attempts",
      description: "N:1 request · UQ attempt_no",
      detail: "WRITE · VERIFY · FINALIZE",
      tone: "danger",
      icon: "ledger",
      width: 170,
    }),
  ],
  edges: [
    link("model-device-inbound", "m-devices", "m-inbounds", {
      sourceHandle: "bottom-source",
      targetHandle: "top-target",
      label: "1:N",
      style: requestStyle,
    }),
    link("model-inbound-inspection", "m-inbounds", "m-inspections", {
      sourceHandle: "bottom-source",
      targetHandle: "top-target",
      label: "1:N",
      style: requestStyle,
    }),
    link("model-device-inventory", "m-devices", "m-inventory", {
      label: "1:0..1",
      style: reliableStyle,
    }),
    link("model-sku-balance", "m-skus", "m-balances", {
      sourceHandle: "bottom-source",
      targetHandle: "top-target",
      label: "1:N",
      style: reliableStyle,
    }),
    link("model-balance-movement", "m-balances", "m-movements", {
      sourceHandle: "bottom-source",
      targetHandle: "top-target",
      label: "1:N",
      style: reliableStyle,
    }),
    link("model-order-allocation", "m-orders", "m-allocation", {
      sourceHandle: "bottom-source",
      targetHandle: "top-target",
      label: "1:N",
      style: processingStyle,
    }),
    link("model-device-allocation", "m-devices", "m-allocation", {
      sourceHandle: "right-source",
      targetHandle: "left-target",
      label: "PG",
      style: backgroundStyle,
    }),
    link("model-sku-allocation", "m-skus", "m-allocation", {
      label: "SKU",
      style: backgroundStyle,
    }),
    link("model-allocation-member", "m-allocation", "m-members", {
      label: "1:N history",
      style: processingStyle,
    }),
    link("model-group-member", "m-groups", "m-members", {
      sourceHandle: "bottom-source",
      targetHandle: "top-target",
      label: "1:N",
      style: processingStyle,
    }),
    link("model-group-carrier", "m-groups", "m-carrier", {
      label: "1:N revisions",
      style: externalStyle,
    }),
    link("model-allocation-sales", "m-allocation", "m-sales", {
      sourceHandle: "top-source",
      targetHandle: "top-target",
      label: "1:0..1",
      style: successStyle,
    }),
    link("model-order-return", "m-orders", "m-returns", {
      sourceHandle: "bottom-source",
      targetHandle: "top-target",
      label: "1:N",
      style: externalStyle,
    }),
    link("model-return-link", "m-returns", "m-return-allocation", {
      label: "1:N",
      style: externalStyle,
    }),
    link("model-return-allocation", "m-allocation", "m-return-allocation", {
      sourceHandle: "bottom-source",
      targetHandle: "left-target",
      label: "allocation_id",
      style: dangerStyle,
    }),
    link("model-request-target", "m-write-request", "m-write-target", {
      sourceHandle: "bottom-source",
      targetHandle: "top-target",
      label: "1:N",
      style: reliableStyle,
    }),
    link("model-request-attempt", "m-write-request", "m-write-attempt", {
      sourceHandle: "bottom-source",
      targetHandle: "top-target",
      label: "1:N attempts",
      style: dangerStyle,
    }),
    link("model-carrier-request", "m-carrier", "m-write-request", {
      label: "optional FK",
      style: backgroundStyle,
    }),
  ],
  legend: [
    { label: "현재 상태·업무 관계", tone: "solid" },
    { label: "선택적 참조와 파생 연결", tone: "dashed" },
    { label: "불변 이력·시도·반품 연결", tone: "danger" },
  ],
};

export const detailedDiagrams: ArchitectureDiagram[] = [
  codeStructureDiagram,
  businessDataFlowDiagram,
  safeExternalWriteDiagram,
  workerRecoveryDiagram,
  coreDataModelDiagram,
];
