import type { MessageShape } from "@/quickhack_shared/i18n/message-contract";
import type { CatalogMessages } from "../ko/catalog.ts";
export const catalogEn = {
  productCriteria: {
    category: { productModel: "Product / Model code", carrier: "Carrier", storage: "Storage", deviceColor: "Official color", appearanceGrade: "Appearance grade", saleGrade: "Sale grade", warrantyGroup: "Sales warranty", appearanceDefect: "Appearance defect", functionDefect: "Function defect", cameraLens: "Camera magnification", cameraFocusRule: "Camera focus criterion" },
    common: { all: "All", selected: "{count, plural, one {# selected} other {# selected}}", selectAll: "Select all {title}", empty: "No criteria values to display.", saving: "Saving", active: "Active", inactive: "Inactive" },
    camera: { title: "Camera inspection criteria", description: "Select lens magnifications registered as product criteria and assign a focus criterion to each lens.", selectAll: "Select all camera lenses", focus: "Focus criterion", empty: "No camera-lens magnification criteria are registered." },
    relation: { form: "Product relations", formModel: "Relations for {model}", saveFailed: "Could not save related criteria.", verifyFailed: "Could not verify the saved related criteria.", saved: "Saved related criteria.", refreshRequired: "{result} Refresh all criteria to verify them.", open: "Open relations for {model}", otherModel: "another model", model: "Model", modelPlaceholder: "Select a model to edit relations", save: "Save relations", description: "This tab manages storage, official colors, and camera-inspection criteria connected to the model. Edit criterion names on the tab to the left.", cameraSummary: "Current camera criteria: {summary}", storage: "Related storage", color: "Related official colors", emptyModel: "No model criterion is available for editing relations." },
    option: { form: "New product criterion", formSelected: "Product criterion {label}", loadFailed: "Could not load product criteria.", category: "Category", parent: "Parent value", key: "Criterion key", label: "Display value", status: "Status", order: "Order", open: "Open criterion {label}", newOpen: "Create a product criterion", reload: "Reload product criteria", tabOpen: "Open product criteria tab", relationTabOpen: "Open related-criteria editor tab", bootstrapOpen: "Fill missing default product criteria", saveFailed: "Could not save the product criterion.", saved: "Saved the product criterion.", refreshRequired: "{result} Refresh the list to verify it.", bootstrapFailed: "Could not check default criteria.", bootstrapDone: "Checked default product criteria." },
    page: { optionsTab: "Product criteria", relationsTab: "Edit related criteria", search: "Search category, parent, key, or display value", categoryPlaceholder: "Category", allCategories: "All categories", refresh: "Refresh", loading: "Loading criteria values.", editorTitle: "Edit product criterion", editorDescription: "Saved values appear in inspection dropdowns and defect selection criteria.", newValue: "New value", parentPlaceholder: "For example, the part name for a defect", keyPlaceholder: "Model code or unique value", labelPlaceholder: "Value shown on screen", sortOrder: "Sort order", save: "Save criterion", bootstrap: "Fill missing defaults" }
  },
  salesOffer: {
    common: { random: "Random", all: "All", active: "Active", inactive: "Inactive", saving: "Saving" },
    warranty: { twoYear: "2-year warranty", oneYear: "1-year warranty" },
    form: { selected: "Sales offer {code}", new: "New sales offer" },
    message: { criteriaLoadFailed: "Could not load product criteria.", listLoadFailed: "Could not load sales offers.", required: "Select a model and warranty condition.", saveFailed: "Could not save the sales offer.", saved: "Saved the sales offer.", bootstrapFailed: "Could not create default sales offers.", bootstrapResult: "Checked {offers, plural, one {# default sales configuration} other {# default sales configurations}} across {products, plural, one {# model} other {# models}}. Created {created, number}, reactivated {reactivated, number}, unchanged {unchanged, number}." },
    columns: { code: "Offer code", model: "Model", storage: "Storage", color: "Color", warranty: "Warranty", mappings: "Channel mappings", mappingCount: "Mapping count", status: "Status" },
    unsaved: { new: "Create a sales offer", open: "Open sales offer {code}", reload: "Reload sales offers", bootstrap: "Create default sales offers" },
    summary: { total: "Total offers", active: "Active", inactive: "Inactive", mapped: "Connected to channels" },
    toolbar: { search: "Search offer code, model, storage, or color", active: "Active", inactive: "Inactive", all: "All", refresh: "Refresh", bootstrap: "Create default offers", loading: "Loading sales offers.", empty: "No sales offers to display." },
    editor: { title: "Edit sales offer", description: "Manage model, storage, color, and warranty as one sales unit.", add: "Add", code: "Offer code", generated: "Generated when saved", model: "Model", modelSelect: "Select model", storage: "Storage condition", allStorage: "All storage", color: "Color condition", allColor: "All colors", warranty: "Warranty", warrantySelect: "Select warranty", status: "Status", save: "Save offer" }
  }
} as const satisfies MessageShape<CatalogMessages>;
