import type { MessageShape } from "@/quickhack_shared/i18n/message-contract";
import type { DeveloperMessages } from "../ko/developer.ts";
export const developerEn = { responsePerformance: {
  range: { h1: "Last hour", h6: "Last 6 hours", h24: "Last 24 hours", d7: "Last 7 days" }, status: { all: "All statuses", success: "Success", failed: "Failed" },
  duration: { ms: "{value, number}ms", seconds: "{value, number}s", minutesSeconds: "{minutes, number}m {seconds, number}s" },
  operation: { inventory_workspace_read: "Load inventory workspace", inventory_quantity_ledger_read: "Load inventory quantity ledger", inventory_quantity_ledger_movements_read: "Load inventory movements", inventory_inbound_reconciliation_read: "Load inbound reconciliation details", inventory_device_create: "Add inventory", inventory_device_update: "Edit inventory", inventory_device_delete: "Delete inventory", inventory_bulk_correction: "Bulk-edit inventory", inventory_audit_save: "Save inventory audit", inspection_record_save: "Save inspection record", inbound_batch_read: "Load inbound batches", inbound_batch_create: "Create inbound batch", inbound_batch_update: "Update inbound batch", inbound_batch_delete: "Delete inbound batch", inbound_purchase_confirm: "Confirm purchase", inbound_purchase_price_save: "Save purchase price", shipment_orders_read: "Load shipment orders", shipment_delivering_read: "Load in-transit shipments", shipment_print_history_read: "Load shipment print history", shipment_inventory_candidates_read: "Load shipment inventory candidates", shipment_address_change_read: "Load address changes", shipment_packing_check: "Verify packing", shipment_print_batch_create: "Create shipment list", shipment_print_batch_update: "Update shipment list status", return_action: "Process return", return_list_read: "Load return list", statistics_dashboard_read: "Load statistics dashboard", statistics_sales_read: "Load sales statistics", sales_channel_sync_check_read: "Load sales-channel sync reviews", sales_channel_sync_check_recheck_inventory: "Recheck sales-channel inventory", sales_channel_sync_check_repair_inventory: "Repair sales-channel inventory", sales_channel_write_review_action: "Process sales-channel write review" },
  span: { empty: "No detailed spans were recorded.", count: "{count, plural, one {# occurrence} other {# occurrences}}", note: "Parent and child spans may both be recorded, so their summed time may not equal total time." },
  columns: { operation: "Operation", samples: "Samples", sampleResult: "{success, number} succeeded / {failed, number} failed", average: "Average", max: "Longest", queryAverage: "Average total DB", txAverage: "Average TX entry", clientSamples: "Client samples", clientCoverage: "{count, number} / {coverage, number}%", clientAverage: "Client average", outsideAverage: "Average outside server", startedAt: "Started at", status: "Status", total: "Total", query: "Total DB", tx: "TX entry", clientTotal: "Client total", outside: "Outside server", target: "Targets", count: "{count, plural, one {# item} other {# items}}" },
  summary: { measured: "Measured samples", success: "Successful samples", failed: "Failed samples", slow: "1 second or longer", p50: "Sample P50", p95: "Sample P95", max: "Longest" },
  notice: { production: "Fast successful requests are sampled in production. Displayed counts and distributions are not full-traffic statistics.", truncated: "Aggregated the latest {analyzed, number} samples out of {matched, number} matching requests.", ingestion: "Performance-log ingestion: {pending, number} pending / {dropped, number} dropped{failure}" },
  filter: { range: "Performance query range", status: "Performance request status", operation: "Performance operation type", allOperations: "All operations", search: "Search performance traces", searchPlaceholder: "Search operation, API route, Trace ID, or error", refresh: "Refresh" },
  operationPanel: { title: "Server performance by operation", subtitle: "Compares successful-sample latency with accumulated DB spans measured inside each trace.", count: "{count, plural, one {# operation} other {# operations}}", loading: "Loading performance samples.", empty: "No operations were measured." },
  tracePanel: { title: "Request traces", subtitle: "Recent request samples recorded by the server.", count: "{count, plural, one {# trace} other {# traces}}", loading: "Loading performance traces.", empty: "No traces match these conditions." },
  detail: { title: "Trace details", subtitle: "Review total time, DB, transactions, and detailed spans.", loading: "Loading details.", select: "Select a trace from the table on the left.", operation: "Operation", copyTrace: "Copy Trace ID", started: "Started", total: "Total time", actor: "Actor", status: "Status", clientGateway: "Client / Gateway", clientGatewayTime: "Client gateway", responseHeader: "Response headers received", responseComplete: "Response consumed", body: "Body processing", outside: "Outside-server segment", outsideNote: "The outside-server segment subtracts the central server trace from client response completion. It is shown as '-' rather than zero when no client sample exists.", dbTx: "DB / Transactions", query: "Queries", totalQuery: "Total DB queries", longestQuery: "Longest query", transaction: "Transactions", txCallback: "TX callback entry", txExecution: "TX execution", dbNote: "Parallel query times are summed, so total DB time may exceed the response time. TX callback entry is not equivalent to DB lock wait time.", spans: "Detailed spans", environment: "Runtime environment", errorCode: "Error code", error: "Error" },
  error: { report: "Could not load response-performance records.", detail: "Could not load performance trace details." },
  system: "System",
}, tools: {
  common: { check: "Check", loading: "Loading.", yes: "Yes", no: "No", allowed: "Allowed", blocked: "Blocked", developer: "Developer", normal: "Normal", warning: "Needs review", exists: "Exists", missing: "Missing", invalidJson: "Could not read the response as JSON. ({status, number})", requestFailed: "The API request failed. ({status, number})" },
  roles: { viewer: "View only", staff: "Staff", manager: "Manager", leader: "Leader" },
  diagnostics: { user: "Signed-in user", environment: "Runtime environment", production: "Production", development: "Development", node: "Node runtime", connected: "Connected", workerSummary: "Registered {registered, number} / DB {persisted, number} / Running {running, number}", hasErrors: "Has errors", menuAccess: "Menu access", devices: "Device data", workerFailures: "Worker failures", otpKey: "OTP key", title: "Current runtime status", checkedAt: "Last checked: {date}", description: "Calls the server diagnostics API.", refresh: "Refresh diagnostics", tableCounts: "Key table counts", workerErrors: "Worker errors" },
  sandbox: { form: "Developer API sandbox request", title: "Compose request", description: "Only internal APIs can be called. The server blocks protected APIs and recursive calls.", writeAllowed: "Writes allowed", readFirst: "Read first", run: "Run request", allowWrite: "Allow write requests such as POST, PATCH, and DELETE.", requestJson: "Request JSON", response: "Response", responsePlaceholder: "The response appears here.", rules: "Sandbox protection rules", internalOnly: "Only internal /api paths", internalOnlyDescription: "Blocks external URLs and SSRF risks.", authBlocked: "Authentication and OTP APIs blocked", authBlockedDescription: "Login, logout, OTP enrollment, and OTP verification APIs cannot be called directly.", writeConfirm: "Confirm write requests", writeConfirmDescription: "The checkbox must be enabled before the server runs a write method." },
  adb: { api: "ADB API", apiReady: "Responding", apiWaiting: "Waiting", connected: "Connected devices", unavailable: "Offline/unauthorized", emulator: "Emulators", title: "ADB devices", description: "Queries ADB devices connected to the current runtime.", refresh: "Refresh ADB", serial: "ADB serial", status: "Status", model: "Model code", carrier: "Carrier", storage: "Storage", firstCall: "First call date", camera: "Camera", warning: "Warning", warningText: { carrierReview: "Carrier requires review", accountReview: "Account requires review", accountQueryFailed: "Account query failed", offline: "ADB status: offline\nReconnect USB or restart the ADB server.", unauthorized: "ADB status: unauthorized\nApprove USB debugging on the phone.", unknown: "ADB status: {state}", queryFailed: "ADB query failed:\n{detail}" }, empty: "No ADB devices to display." },
  database: { title: "Database status", checkedAt: "Last checked: {date}", description: "Queries PostgreSQL and Prisma status.", refresh: "Check status", file: "Database file", integrity: "PostgreSQL constraint integrity", applied: "{count, plural, one {# applied} other {# applied}}", tableMissing: "Table missing", queried: "Queried", caution: "Caution", migrations: "Migration files", noSql: "No SQL", noMigrations: "No migration files were found or queried yet.", tables: "Key tables" }
} } as const satisfies MessageShape<DeveloperMessages>;
