import type { MessageShape } from "@/quickhack_shared/i18n/message-contract";
import type { ReturnsMessages } from "../ko/returns.ts";

export const returnsEn = {
  actionDraft: { target: "Process return", form: "Return-processing input" },
  format: { modelSequence: "No. {value, number}" },
  message: { actionComplete: "Return processing is complete.", actionFailed: "Failed to complete return processing.", loadFailed: "Failed to load returns.", reviewRequired: "Coupang status could not be confirmed automatically. The request was moved to sales-channel synchronization review.", actionMismatch: "Only the {action} action is available for the current receipt status." },
  actions: { cancel: "Cancel", loadMore: "Show more returns", loading: "Loading", processing: "Processing", refresh: "Refresh list", reviewRequired: "API review required", stopShipment: "Complete shipment stop", receiveConfirm: "Confirm receipt", approve: "Complete return" },
  columns: { action: "Action", address: "Address", inventoryStatus: "Inventory status", orderAt: "Ordered at", orderId: "Order ID", product: "Product", reason1: "Reason 1", reason2: "Reason 2", reason3: "Reason 3", receiptStatus: "Receipt status", receiver: "Recipient", shipmentBatch: "Shipment batch" },
  inspection: { appearanceDefect: "Appearance defect", appearanceDefectPlaceholder: "Example: screen dent", appearanceGrade: "Appearance grade", appearanceGradePlaceholder: "Example: A, B, damaged", description: "Records the inspection result for each selected PG while completing the return.", functionDefect: "Functional defect", functionDefectPlaceholder: "Example: charging failure", note: "Inspection note", notePlaceholder: "Packaging, missing accessories, and resale rationale", result: { disposal: "Dispose", failed: "Defective", hold: "Hold", passed: "Resellable", returnToSupplier: "Return to supplier" }, title: "Return inspection" },
  modal: { allocation: "PG assignment", cancelCount: "Return quantity", candidateEmpty: "No matched PG can be linked to this return receipt. Coupang return processing continues without a PG link.", description: "Select linkable PGs, then {action}.", footerLocked: "Return completion must use the same PGs linked during receipt confirmation.", footerNoCandidate: "Orders without a matched PG continue Coupang processing without a PG link.", footerSelection: "The Coupang action becomes available when the number of linked PGs matches the selectable quantity.", item: "Shipment {shipmentId} · Item {itemId}", missing: "{count, number} links missing", orderId: "Order ID", receiptId: "Receipt ID", select: "{selected, number} / {required, number} selected", title: "Select return PGs", unit: "{count, plural, one {# unit} other {# units}}" },
  phase: { after: { empty: "No Coupang returns match the post-shipment criteria.", loading: "Loading post-shipment returns.", title: "Post-shipment returns" }, before: { empty: "No Coupang returns match the pre-shipment criteria.", loading: "Loading pre-shipment returns.", title: "Pre-shipment returns" } },
  receiptStatus: { completed: "Return completed", confirm: "Confirm receipt", receipt: "Return received", requestCheck: "Request Coupang review", stop: "Request shipment stop" },
  summary: { after: "Post-shipment", before: "Pre-shipment", coverage: "The receipt count covers all results; other linked totals cover only the loaded pages.", linkedOrders: "Linked orders", linkedShipments: "Linked shipments", matchedPg: "Matched PGs", receipts: "Receipts", statusCheck: "Status checks" },
  supplies: { description: "Select only reusable supplies deducted from the original shipment.", empty: "No supply-consumption history exists for this shipment.", recovered: "Recovered", recoverOnReturn: "Restore inventory on return", title: "Recovered supplies", unavailable: "Not reusable", unit: "{count, plural, one {# item} other {# items}}" },
} as const satisfies MessageShape<ReturnsMessages>;
