import type { MessageShape } from "@/quickhack_shared/i18n/message-contract";
import type { SalesChannelMessages } from "../ko/sales-channel.ts";
export const salesChannelEn = { orderMatching: {
  fallback: { rematchExecuteFailed: "Failed to complete the existing-order rematch.", rematchPreviewFailed: "Failed to load existing-order rematch targets." },
  rematchExclusion: { SHIPMENT_NOT_FULLY_MATCHED: "Not every item in the shipment is fully matched", CURRENT_MAPPING_UNAVAILABLE: "No current default product mapping is available", ALLOCATION_QUANTITY_MISMATCH: "Order quantity differs from active PG allocation quantity", ALLOCATION_NOT_REVERSIBLE: "A PG allocation has already been print-confirmed", INVENTORY_NOT_RESERVED: "PG inventory is not in the order-confirmed state", OUTBOUND_HANDOFF_STARTED: "A print batch or combined-package operation has started", WRITE_REQUEST_PENDING: "External API processing or review is in progress", RETURN_FLOW_EXISTS: "A return is in progress or linked history exists", SALES_RECORD_EXISTS: "A sales ledger record already exists", ORDER_STATUS_NOT_REVERSIBLE: "The Coupang order has passed the rematchable stage", SNAPSHOT_INCONSISTENT: "Order, offer, and PG allocation snapshots do not agree" },
  common: { mapped: "Mapped", unmapped: "Unmapped", all: "All", active: "Active", inactive: "Inactive", allStorage: "All storage", allColor: "All colors", allValue: "All", noMapping: "No mapping", noLocation: "No location", noInventory: "No inventory", noStatus: "No status", count: "{count, plural, one {# item} other {# items}}", devices: "{count, plural, one {# device} other {# devices}}" },
  summary: { options: "Coupang options", mapped: "Mapped", unmapped: "Unmapped", offers: "Active offers" },
  toolbar: { search: "Search vendorItemId, product, model, warranty, storage, or color", refresh: "Refresh", preview: "Review rematch targets" },
  columns: { option: "Coupang option", productOption: "Product / Option", offer: "Sales offer", offerCondition: "Model / Conditions / Warranty", storageCondition: "Storage condition", storage: "Storage", colorCondition: "Color condition", color: "Color", status: "Status", orders: "Orders", orderCount: "Order count" },
  detail: { title: "Channel-order matching criteria", subtitle: "Connect Coupang vendorItemIds to QuickHack model/warranty combinations and storage/color conditions.", option: "Coupang option", productName: "Product name", updated: "Last updated", offer: "Sales offer", offerSearch: "Search model, storage, color, or warranty conditions", offerCode: "Offer code", model: "Model", storage: "Storage", color: "Color", warranty: "Warranty condition", offerStatus: "Offer status", saving: "Saving", save: "Save match", clear: "Clear mapping", previewing: "Loading", inventoryPreview: "Preview inventory candidates", candidates: "{count, plural, one {# inventory candidate} other {# inventory candidates}}", noCandidates: "No inventory candidates were found.", select: "Select a Coupang option from the table on the left." },
  grid: { loading: "Loading Coupang product mappings.", empty: "No Coupang product mappings to display." },
  message: { candidateLoadFailed: "Failed to load inventory candidates.", mappingLoadFailed: "Failed to load Coupang product mappings.", offerLoadFailed: "Failed to load sales offers.", rematchComplete: "Released {allocations, plural, one {# existing allocation} other {# existing allocations}} and rematched {shipments, plural, one {# shipment} other {# shipments}}. {completed, number} completed, {partial, number} partial, and {failed, number} failed.", rematchAfterResetFailed: "The previous allocations were released safely, but immediate rematching did not complete. Review the order-matching status.", saveFailed: "Failed to save the matching criteria.", saved: "Saved the matching criteria and applied them to {updated, plural, one {# changeable order} other {# changeable orders}}.", savedWithProtected: "Saved the matching criteria and applied them to {updated, plural, one {# changeable order} other {# changeable orders}}. {protected, plural, one {# order with progress or completion history retained} other {# orders with progress or completion history retained}} the existing mapping.", unchanged: "The matching criteria are unchanged. No stored data was modified." },
  candidateWarning: { CANDIDATE_LOAD_FAILED: "Failed to load inventory candidates.", ACTIVE_OFFER_NOT_FOUND: "No active sales offer was found.", INVALID_WARRANTY_GROUP: "The sales offer has an invalid warranty condition.", MAPPING_NOT_FOUND: "The Coupang product-mapping row was not found.", MAPPING_REQUIRED: "Inventory candidates are unavailable until the product combination is mapped.", MAPPED_OFFER_INACTIVE: "The linked sales offer is missing or inactive.", RANDOM_STORAGE_BUCKET: "One storage candidate group was selected by the random-storage rule.", RANDOM_COLOR_BUCKET: "One color candidate group was selected by the random-color rule.", GRADE_FALLBACK: "No inventory matched the default {warrantyGroup} priority, so grades {grades} were queried." },
  rematch: { title: "Review existing-order rematch targets", subtitle: "Review matched shipments not yet handed to shipment work. After reviewing the full list, rematch them in a separate confirmation step.", allPages: "Review every page before rematching.", revalidate: "Only eligible targets are locked and revalidated at execution time.", close: "Close", executeCount: "Rematch {count, plural, one {# target} other {# targets}}", reviewed: "Shipments reviewed", eligible: "Rematch targets", excluded: "Excluded", targetPg: "Target PGs", reasons: "Exclusion reasons", privacy: "Evaluates all items by order and shipment number. Recipient, address, and phone data are not queried.", basis: "As of {date}", empty: "There are no matched shipments to review.", order: "Order {id}", shipment: "Shipment {id}", shipmentSummary: "Coupang {status} · {items, plural, one {# item} other {# items}} · {allocations, plural, one {# PG} other {# PGs}}", quantity: "vendorItemId {id} · Quantity {quantity, number}", snapshot: "Existing order snapshot", current: "Current default mapping", retry: "Re-evaluate", more: "Show more targets", loading: "Evaluating rematch targets and exclusion reasons.", confirmTitle: "Rematch existing unpacked orders", confirmDescription: "Release existing PG allocations for every displayed target and rematch using current default product mappings. Abort the entire operation if state changed after display.", confirmSummary: "{shipments, plural, one {# shipment} other {# shipments}} · {items, plural, one {# order item} other {# order items}} · {allocations, plural, one {# PG} other {# PGs}}", confirmNote: "Recheck order numbers, shipment numbers, and PGs before execution.", confirm: "Release allocations and rematch", busy: "Rematching", refreshed: "Order state changed during review, so the list was refreshed from the first page." }
}, policy: {
  basis: {
    saleGrade: { label: "Sale-grade priority", value: "The policy's sale-grade priority" },
    stockAge: { label: "Inventory registration time", value: "Select by inventory registration time" },
  },
  rules: {
    orderCanceled: { label: "Cancellation", value: "Order item is not canceled", note: "Canceled order items are excluded from automatic matching." },
    matchableQuantity: { label: "Matchable quantity", value: "matchable_quantity > 0", note: "Only items with a remaining shippable quantity are processed." },
    mappingStatus: { label: "Product mapping status", value: "MAPPED", note: "The channel product must be connected to a QuickHack sales offer." },
    salesOffer: { label: "Sales offer", value: "sales_offer_id required", note: "Only orders with confirmed model, option, and warranty-group conditions are matched automatically." },
    inventoryStatus: { label: "Inventory status", value: "Sellable inventory", note: "Only inventory confirmed after purchasing and available for sale is considered." },
    shipmentHistory: { label: "Shipment history", value: "No active match", note: "PGs already in the order-matching flow are excluded." },
    existingMatch: { label: "Existing order match", value: "No active match", note: "Prevents a PG assigned to another order from being reserved twice." },
    model: { label: "Model", value: "model", note: "The sales-offer model must match the inventory SKU model." },
    storage: { label: "Storage", value: "storage", note: "The sales offer's storage condition is applied to the candidate query." },
    warrantyGroup: { label: "Warranty group", value: "warrantyGroup", note: "Sale-grade priority is applied according to the warranty group." },
  },
  worker: {
    name: { label: "Worker", value: "Order inventory matching", note: "This worker combines sales-channel orders and matches inventory." },
    interval: { label: "Default interval", value: "120 seconds", note: "The schedule can be enabled or disabled in System Status." },
    batch: { label: "Batch size", value: "Up to 100 order items", note: "Maximum number processed in one worker run." },
  },
  common: { readOnly: "Read only", saved: "Custom", default: "Default", stopped: "Stopped", allStorage: "All storage", allColor: "All colors" },
  filter: { title: "Candidate filter order", order: "Top to bottom", direction: "Inventory selection direction", recentFirst: "Newest inventory first", oldFirst: "Oldest inventory first" },
  list: { empty: "No sales offers to display.", mappings: "Mappings {count, number}", orders: "Orders {count, number}" },
  tier: { title: "Sale-grade candidate priority", description: "Select a grade to include it, and drag selected grades to change their order.", rank: "Priority {rank, number}", excluded: "Excluded" },
  editor: { select: "Select a sales offer.", individualPolicy: "Custom policy", defaultPolicy: "Default policy", reset: "Reset", save: "Save", offer: "Sales offer", model: "Model", warrantyGroup: "Warranty group", mappingOrders: "Channel mappings / Orders", mappingOrdersValue: "{mappings, number} / {orders, number}", policyName: "Policy name", policyNamePlaceholder: "Example: Prioritize S24 2-year warranty A", autoMatch: "Enable automatic matching for this sales offer", gradeFallback: "Automatically search subsequent grades" },
  message: { loadFailed: "Could not load order-matching policies.", loaded: "Loaded {count, plural, one {# sales-offer policy} other {# sales-offer policies}}.", saveFailed: "Could not save the order-matching policy.", saved: "Saved the sales-offer order-matching policy.", reset: "Reset the sales-offer policy to its default." },
  unsaved: { form: "Order-matching policy", formOffer: "Order-matching policy for {offer}", open: "Open the order-matching policy for {offer}", reload: "Reload order-matching policies" },
  page: { title: "Sales-offer priority policies", description: "Set the inventory-candidate search order for each QuickHack sales-product combination.", individualCount: "{count, plural, one {# custom policy} other {# custom policies}}", refresh: "Refresh", searchPlaceholder: "Search offer code, model, storage, or color", total: "Total", individual: "Custom", search: "Results", loading: "Loading sales-offer policies." },
  sections: {
    orderTitle: "Fixed order-item conditions", orderDescription: "Conditions the automatic-matching worker must check before processing an order item.",
    inventoryTitle: "Fixed candidate-inventory conditions", inventoryDescription: "Conditions a physical PG must satisfy before it can be reserved for an order.",
    matchingTitle: "Sales-product combination criteria", matchingDescription: "Narrows inventory candidates using the channel product mapping and QuickHack sales-product combination.",
    flowTitle: "Automatic-matching flow", currentCode: "Current code",
    step1: { title: "Check order target", text: "First check cancellation, quantity, product mapping, and sales-product combination conditions." },
    step2: { title: "Query candidate inventory", text: "Load only sellable PGs with no shipment or active match." },
    step3: { title: "Reserve PG", text: "Change the selected PG's inventory status to reserved and record the match history." },
    step4: { title: "Update order status", text: "Recalculate matching status for the item, shipment, and full order." },
    safety: "Sales-offer policies only change candidate-search priority. Safety conditions such as excluding canceled orders, using only sellable inventory, and excluding shipped or matched PGs cannot be changed here.",
    implementation: "At this stage, the policy storage model and UI are in place. Connecting the automatic-matching worker so it applies these policies to candidate queries is the next step."
  }
}, manualMatch: {
  title: "Order change requests", description: "Only orders already received through a sales channel can be processed. For independent shipments, place the inventory item on hold in inventory editing.", searchPlaceholder: "Search order ID, shipment ID, or product", search: "Search", empty: "No sales-channel orders found.", recovery: "Recovery required: {reason}", selectOrder: "Select an order item to change.", shipment: "Shipment {id} · {item}", noPg: "No PG",
  workStatus: { UNMATCHED: "Waiting for match", MATCHED: "Matched", PARTIAL: "Partially matched", FAILED: "Match failed", SKIPPED: "Excluded from matching", EXPIRED: "Match expired", unknown: "Unknown match status ({code})" },
  allocationStatus: { ALLOCATED: "PG allocated", API_ACKED: "Sales channel acknowledged", SHIPMENT_LIST_PRINTED: "Shipment list printed", CANCELED: "Allocation canceled", unknown: "Unknown allocation status ({code})" },
  recoveryStatus: { reassignmentRequired: "PG reassignment required" },
  form: { operation: "Action", assign: "Assign PG", replace: "Replace PG", release: "Release PG", currentPg: "Current PG", newPg: "New PG", pgSearch: "Search sellable PG", requestChannel: "Request channel", coupang: "Coupang inquiry", phone: "Phone inquiry", other: "Other", reason: "Reason for change" },
  permission: { readOnly: "STAFF can view only. Changes require MANAGER access and OTP verification.", disabled: "Order PG changes are disabled in operations settings. You can preview the impact only." },
  message: { candidatesLoadFailed: "Could not load PG candidates.", listLoadFailed: "Could not load the list.", previewFailed: "Could not preview the change impact.", executeFailed: "Could not execute the PG change.", postCyclePending: "The PG change was applied and sales-channel follow-up is in progress.", postCycleFailed: "The PG change was applied, but sales-channel follow-up did not complete. Review the order-matching status.", executeComplete: "The order PG change and follow-up processing were applied." },
  reason: { allocationNotFound: "The current allocation could not be found.", allocationNotReversible: "The allocation cannot be changed at its current stage.", shipmentListPrinted: "The shipment list has already been printed.", activePackageGroup: "The item belongs to an active package group.", salesRecorded: "The sale has already been finalized.", returnStarted: "Return processing has started.", channelWritePending: "A sales-channel write is in progress.", carrierShipmentExists: "Tracking or delivery processing has already started.", carrierOperationActive: "A carrier tracking allocation, registration, or replacement operation is in progress.", shipmentAddressChangeActive: "A delivery-address change request is in progress.", matchQuantityConflict: "The full required order quantity is already allocated.", pgNotSellable: "The selected PG is not sellable.", pgAlreadyAllocated: "The selected PG is already allocated to this order.", pgNotFound: "The selected PG could not be found.", orderStateNotEligible: "The PG cannot be changed in the current sales-channel order state.", pgSelectionRequired: "Select the PG again from the current order's search results.", orderItemCanceled: "A canceled order item cannot be assigned or replaced.", manualReassignmentRequired: "Shipment is blocked until PG reassignment is complete." },
  preview: { action: "Preview impact", eligible: "Change allowed", ineligible: "Change blocked", selected: "Selected PG {pg} · {model} {storage} {color}", difference: "{field}: ordered {required} → shipping {actual}", confirmLabel: "Confirm order PG change", execute: "Execute" },
}, channelProducts: {
  common: { mapped: "Mapped", unmapped: "Unmapped" },
  columns: { product: "Product", productName: "Product name", productId: "Product ID", option: "Options", optionName: "Option name", mapping: "Mapping", orders: "Orders", available: "Available", updated: "Updated", updatedAt: "Updated at", status: "Status", offer: "Sales offer", offerShort: "Offer", storage: "Storage", color: "Color" },
  message: { loadFailed: "Could not load channel products.", incomplete: "The full Coupang product list could not be verified, so the existing list was kept." },
  summary: { products: "Products", options: "Options", mapped: "Mapped", unmapped: "Unmapped" },
  toolbar: { search: "Search product name, product ID, vendorItemId, or option name", all: "All", fullyMapped: "Fully mapped", includesUnmapped: "Includes unmapped", refresh: "Refresh", loading: "Loading channel products.", empty: "No channel products to display." },
  detail: { selectTitle: "Select product", readOnly: "Read only", channel: "Channel", productId: "Product ID", options: "Options", optionCount: "{count, plural, one {# option} other {# options}}", mapping: "Mapping", orderItems: "Order items", orderCount: "{count, plural, one {# item} other {# items}}", available: "Available quantity", lastOrder: "Last order", updated: "Recently updated", emptyOptions: "No options to display.", select: "Select a product." }
} } as const satisfies MessageShape<SalesChannelMessages>;
