export const settingsEn = {
  personal: {
    tabs: { account: "Account", personal: "Personal", appearance: "Appearance" }, account: { loading: "Loading account information.", basic: "Basic information", mine: "My account", role: "Role", createdAt: "Account created", dirty: "There are unsaved account changes.", saved: "Saved.", cancel: "Cancel changes", saving: "Saving", save: "Save account" }, role: { viewer: "View only", staff: "Staff", manager: "Manager", leader: "Leader" },
    loading: "Loading personal settings.", shortcuts: {
      title: "Shortcuts", enabled: "Enable shortcuts", top: "Top-level navigation", current: "Within current menu", common: "Common actions", clear: "Clear shortcut", modifier: "{action} modifier", key: "{action} key", press: "Press a key", unset: "Not assigned", unassigned: "Not assigned", error: { unsupported: "This key is not supported.", reserved: "This shortcut conflicts with a Windows or browser default.", duplicate: "This shortcut is assigned to another action." },
      guide: { title: "Keyboard shortcuts", description: "Shortcuts saved for the current account.", sections: { common: "Common actions", top: "Top-level navigation", current: "Within the current menu" } },
      modifiers: { none: "None", ctrl: "Ctrl", shift: "Shift", alt: "Alt" },
      action: { navigateMain: "Open Main", navigateInbound: "Open Inbound", navigateInventory: "Open Inventory", navigateShipment: "Open Shipment", navigateReturns: "Open Returns", navigateInvoice: "Open Invoice management", navigateSupplies: "Open Supplies", navigateStats: "Open Statistics", navigateSystemAdmin: "Open System administration", navigateDeveloper: "Open Developer menu", currentItem01: "Open item 1 in the current menu", currentItem02: "Open item 2 in the current menu", currentItem03: "Open item 3 in the current menu", currentItem04: "Open item 4 in the current menu", currentItem05: "Open item 5 in the current menu", currentItem06: "Open item 6 in the current menu", currentItem07: "Open item 7 in the current menu", currentItem08: "Open item 8 in the current menu", currentItem09: "Open item 9 in the current menu", currentItem10: "Open item 10 in the current menu", currentItem11: "Open item 11 in the current menu", focusSearch: "Focus search", closeWindow: "Close window", refreshList: "Refresh list", openPersonalSettings: "Open personal settings", openShortcutGuide: "Open keyboard shortcuts" },
    }, notifications: { title: "Notifications", windows: "Desktop notifications", inspection: "Inspection completed", shipment: "Delivery information changed", returns: "Return received" }, status: { dirty: "There are unsaved changes.", saved: "Saved." }, actions: { defaults: "Defaults", cancel: "Cancel changes", saving: "Saving", save: "Save" }
  },
  accountTotp: {
    recoveryLabel: "My OTP recovery codes", title: "OTP two-factor authentication", description: "Verify your identity with a six-digit authenticator code when opening sensitive menus.", status: { checking: "Checking", configured: "Configured", unconfigured: "Not configured" },
    message: { statusFailed: "Could not check OTP status.", qrFailed: "Could not create the QR code. Enter the enrollment key manually.", actionFailed: "Could not process the OTP action.", setupMissing: "OTP enrollment information was not returned.", enterCode: "Register it in your authenticator app, then enter the displayed six-digit code.", confirmFailed: "Could not complete OTP enrollment.", confirmed: "OTP enrollment is complete. Store the recovery codes somewhere safe now.", credentialsRequired: "Enter both your current password and six-digit OTP code.", disabled: "OTP two-factor authentication was disabled.", recoveryIssued: "New recovery codes were issued.", codeInvalid: "The OTP code is invalid.", notConfigured: "OTP is not configured for this account.", actionUnsupported: "This OTP request is not supported.", authRequired: "Sign in is required.", invalidBody: "The request body is invalid.", rateLimited: "OTP verification is locked. Try again in {seconds, plural, one {# second} other {# seconds}}." },
    guarded: { confirm: "Complete OTP enrollment", disable: "Disable OTP two-factor authentication", recovery: "Reissue OTP recovery codes", disableConfirm: "Disable OTP two-factor authentication for this account?" },
    unavailable: "OTP enrollment and protected actions are blocked because the OTP security service is unavailable. An administrator must check OTP security status from the primary QuickHack server console.",
    setup: { password: "Current password", start: "Start OTP enrollment", qrAlt: "OTP enrollment QR code", qrLoading: "Creating QR code", qrHint: "Scan the QR code in your authenticator app.", secret: "Authenticator enrollment key", code: "Six-digit authenticator code", confirm: "Complete OTP enrollment" },
    management: { verifiedAt: "Enrolled at", lockedUntil: "Lock expires", recoveryRemaining: "Recovery codes remaining", recoveryCount: "{count, plural, one {# code} other {# codes}}", password: "Current password", code: "Current six-digit OTP code", reissue: "Reissue recovery codes", disable: "Disable OTP" },
  },
  mobileApp: {
    formLabel: "Register packing inspection USB device", title: "Packing inspection mobile connection", description: "Enrollment credentials are sent only to the currently connected physical USB device. Enrollment codes are not displayed.",
    permission: { allowed: "Access allowed", denied: "No access", message: "You do not have packing inspection access." },
    state: { active: "Active", provisioning: "Waiting for app sign-in", reauthRequired: "Re-enrollment required", revoked: "Revoked" },
    message: { loadFailed: "Could not load mobile device registrations.", adbLoadFailed: "Could not load the ADB device list.", adbUpdated: "The list of ready physical USB devices was refreshed.", adbEmpty: "There are no ready physical USB devices.", selectDevice: "Refresh the ADB list and select a physical USB device.", provisionFailed: "Could not enroll the USB device.", provisioned: "Enrollment information was sent to the USB device.", revokeFailed: "Could not revoke the device registration.", revoked: "The device registration was revoked." },
    revokeConfirm: "Revoke the registration for {device}?", device: "Physical USB ADB device", select: "Select an ADB device", refresh: "Refresh ADB", label: "Device label", labelPlaceholder: "Example: Packing line device 1", register: "Register selected USB device", revision: "Revision {revision, number}", activatedAt: "Activated", lastSeenAt: "Last seen", reregister: "Re-enroll on selected USB", revoke: "Revoke", empty: "This account has no registered packing inspection devices.", loadMore: "Load more registrations",
  },
  language: {
    description: "Applied to QuickHack menus and system messages after saving.",
    english: "English",
    korean: "한국어",
    label: "Display language",
    title: "Language",
  },
} as const;
