import type { MessageShape } from "@/quickhack_shared/i18n/message-contract";
import type { StatisticsMessages } from "../ko/statistics.ts";

export const statisticsEn = {
  visual: { empty: "No data to aggregate.", lineAria: "{title} line chart", lineWithGapsAria: "{title}. Lines are not connected across missing intervals." },
  periodToolbar: { aria: "Statistics query period", title: "Statistics period", default: "Default 90 days", custom: "Custom", applied: "Applied: {from} – {to} · Through yesterday in Korea Standard Time", from: "Start date", to: "End date", apply: "Apply period", reset: "Return to default 90 days", error: { incomplete: "Enter both the statistics start and end dates.", invalidDate: "The statistics period must contain valid dates in YYYY-MM-DD format.", reversed: "The statistics start date cannot be later than the end date.", openDate: "The statistics end date cannot be later than yesterday in Korea Standard Time.", unknown: "Could not validate the statistics period." } },
  calculationScope: { method: { liveFallback: "Live fallback calculation", live: "Live calculation", snapshot: "Stored daily statistics", automaticFallback: "Automatic stored-statistics fallback", customPeriod: "Custom period", delayed: "{days, plural, one {# day} other {# days}} behind the default cutoff", current: "Default 90 days · latest snapshot", defaultPeriod: "Default 90 days", custom: "Custom" }, fallback: { notFound: "No stored statistics are available yet, so the current ledger was calculated live.", tooOld: "Stored statistics are at least two days old, so the current ledger was calculated live.", invalid: "Stored statistics could not be verified safely, so the current ledger was calculated live." }, delayed: "Stored statistics are {days, plural, one {# day} other {# days}} behind the current default cutoff. The actual data cutoff is {date}.", labels: { method: "Calculation method", period: "Aggregation period", comparison: "Comparison period", cutoff: "Data cutoff" }, days: "{days, plural, one {# day} other {# days}}", comparisonDays: "{days, plural, one {# day} other {# days}} · Same length", cutoffDelayed: "Earlier than the current default cutoff", cutoffCurrent: "Through yesterday in Korea Standard Time" },
  metric: { count: "{count, plural, one {# item} other {# items}}", unit: "items", sample: "{count, plural, one {# sample} other {# samples}}", ratio: "{numerator, number} / {denominator, number}", priceCoverage: "{priced, number} / {total, number} prices confirmed", priceCoveragePercent: "{priced, number} / {total, number} prices confirmed · {coverage, number}%", noSample: "No sample", noSampleAnomaly: "No sample · {count, plural, one {# anomaly excluded} other {# anomalies excluded}}", p90: "P90 {hours, number} hours", p90Unavailable: "P90 -", anomaly: " · {count, plural, one {# anomaly excluded} other {# anomalies excluded}}", hours: "{hours, number} hours", month: "{month, number}/{year, number}", unavailableReason: { NO_DENOMINATOR: "There is no denominator to aggregate.", NO_MATURE_SALES: "There are no mature sales yet.", NO_CONFIRMED_RETURN_FAULT_SAMPLE: "There are no returns with a confirmed fault category.", NO_CONFIRMED_RETURN_INSPECTION_SAMPLE: "There is no confirmed return-inspection sample.", NO_CURRENT_MATURE_COHORT: "There are no mature sales in the current cohort.", NO_PREVIOUS_MATURE_COHORT: "There are no mature sales in the previous cohort.", NO_CURRENT_30_DAY_MATURE_COHORT: "The recent 30-day sales cohort is not fully mature yet.", NO_PREVIOUS_30_DAY_MATURE_COHORT: "There is no previous mature 30-day sales cohort to compare.", NO_RETURN_RECEIPTS: "There are no customer-return receipts matching the query.", NO_MATURE_PURCHASE_BATCHES: "There are no purchase batches that completed the {days, number}-day observation period.", NO_LINKED_INBOUND_INSPECTION_SAMPLE: "There is no linked inbound-inspection sample.", NO_TERMINAL_INBOUND_BATCHES: "There are no terminal inbound batches.", NO_ORIGINAL_SUPPLIER_SALES_SAMPLE: "There are no sales with an original-supplier snapshot.", INVENTORY_LEDGER_UNAVAILABLE: "The inventory ledger cannot be reconstructed for this period.", NO_INVENTORY_OR_SALES: "There is no warehouse inventory or sales in this period.", SALES_WITHOUT_INVENTORY_DENOMINATOR: "Sales exist, but the warehouse-inventory denominator is zero.", SALE_LEDGER_TIMESTAMP_UNVERIFIED: "Sale-ledger timestamps could not be verified." } },
  sales: {
    unknown: { sku: "SKU not recorded", model: "Model not recorded", storage: "Storage not recorded", color: "Color not recorded", grade: "Grade not recorded", warranty: "Warranty not recorded", channel: "Channel not recorded" },
    priceBand: { PRICE_LT_100K: "Below ₩100K", PRICE_100K_199K: "₩100K–199K", PRICE_200K_299K: "₩200K–299K", PRICE_300K_399K: "₩300K–399K", PRICE_400K_499K: "₩400K–499K", PRICE_500K_599K: "₩500K–599K", PRICE_600K_PLUS: "₩600K or more", PRICE_UNKNOWN: "Price unknown" },
    count: "{count, plural, one {# sale} other {# sales}}",
    dimension: { model: "Model", storage: "Storage", color: "Color", grade: "Sale grade", warranty: "Warranty group", channel: "Sales channel" },
    coverage: { title: "Aggregation sources and reliability", subtitle: "Review ledger status and price, cost, and lead-time coverage before interpreting sales statistics.", ledger: "Queried ledger", ledgerDescription: "{count, plural, one {# total ledger row} other {# total ledger rows}}", status: "Sale status", statusValue: "{count, plural, one {# retained sale} other {# retained sales}}", statusDescription: "Includes {count, plural, one {# original sale after return} other {# original sales after return}}", salesPrice: "Sales-price coverage", purchasePrice: "Purchase-cost coverage", profit: "Gross-profit comparison coverage", ratio: "{available, number} / {total, number}", leadSample: "Sales lead-time sample", leadDescription: "{missing, number} missing · {invalid, number} invalid", soldAtExcluded: "Sale timestamps excluded", soldAtDescription: "{invalid, number} invalid · {future, number} future", generatedAt: "Generated at", periodAll: "Entire selected period", warning: "Some statistical data requires review.", success: "No missing data or chronology anomalies require separate review in this range.", excludedStatus: "{count, plural, one {# ledger row was} other {# ledger rows were}} excluded because the sale was not finalized", invalidSoldAt: "{count, plural, one {# ledger row was} other {# ledger rows were}} excluded due to an invalid sale timestamp", futureSoldAt: "{count, plural, one {# ledger row has} other {# ledger rows have}} a future sale timestamp", missingSalesPrice: "{count, plural, one {# sale has} other {# sales have}} no recorded sales price", missingPurchasePrice: "{count, plural, one {# sale has} other {# sales have}} no recorded purchase cost", missingPurchaseAt: "{count, plural, one {# sale has} other {# sales have}} no purchase-confirmation timestamp", invalidLead: "{count, plural, one {# sale was} other {# sales were}} excluded due to invalid lead time" },
    presentation: { priceCoverage: "{priced, number} / {total, number} prices confirmed", margin: "Margin {value}%", marginUnavailable: "Margin -", profitDetail: "{margin} · {comparable, number} / {total, number} comparable · {coverage, number}%", anomaly: " · {count, plural, one {# anomaly excluded} other {# anomalies excluded}}", days: "{days, plural, one {# day} other {# days}}", leadDetail: "{sample, number} / {total, number} samples · {coverage, number}%{anomaly}" },
    summary: { sales: "Confirmed sales", salesDescription: "Based on PGs in the sales ledger", amount: "Sales amount", averagePrice: "Average sales price", purchaseCost: "Purchase cost", grossProfit: "Product gross profit", leadTime: "Average sales lead time" },
    monthly: { chart: "Monthly confirmed sales", title: "Monthly sales performance", subtitle: "Groups original ledger sale dates by Korea Standard Time month.", month: "Month", sales: "Sales", amount: "Sales amount", average: "Average sales price", grossProfit: "Product gross profit" },
    product: { title: "Sales performance by product", subtitle: "Compares product attributes captured in the sales ledger at delivery completion.", model: "Model", storage: "Storage", color: "Color", grade: "Grade", warranty: "Warranty", sales: "Sales", share: "Share", amount: "Sales amount", grossProfit: "Product gross profit", lead: "Sales lead time", days90: "90+ days" },
    composition: { title: "Sales composition", subtitle: "Select one product attribute at a time to compare composition share and amount.", sales: "Sales", share: "Share", amount: "Sales amount", grossProfit: "Product gross profit" },
    priceGrade: { title: "Price band and sale grade", subtitle: "Sales with no recorded price remain in the unknown-price row so coverage loss is visible.", priceBand: "Price band", total: "Total" },
    leadDistribution: { title: "Sales lead-time distribution", subtitle: "Compares only samples measurable from purchase confirmation to the original sale date.", days0_29: "0–29 days", days30_59: "30–59 days", days60_89: "60–89 days", days90Plus: "90 days or more" },
    channel: { title: "Sales-channel performance", subtitle: "Compares channel sales volume and gross profit for products with both price and cost.", channel: "Channel", sales: "Sales", share: "Share", amount: "Sales amount", average: "Average sales price", grossProfit: "Product gross profit", lead: "Sales lead time" },
    loading: { initial: "Loading sales statistics.", aggregating: "Aggregating the sales ledger.", error: "Could not load sales statistics.", retry: "Try again", refresh: "Refreshing statistics with the same conditions. Current results remain visible." }
  },
  inventory: {
    unavailable: { aggregate: "Unavailable", confirm: "Unknown" },
    unit: { count: "{count, plural, one {# item} other {# items}}", row: "{count, plural, one {# row} other {# rows}}", device: "{count, plural, one {# device} other {# devices}}", days: "{count, plural, one {# day} other {# days}}", turns: "{count, number} turns" },
    period: { days30: "Last 30 days", days90: "Last 90 days", year1: "Last year", all: "All time", custom: "Custom", range: "{from} – {to} · {days, plural, one {# day} other {# days}}", sectionTitle: "{period} inventory flow and sales turnover" },
    status: { sellable: "Sellable", allocated: "Order allocated", restricted: "Sales restricted or under review", delivering: "In delivery", trackingException: "Tracking exception", finalDelivery: "Sale finalized", claimUnknown: "Customer claim in progress or location unknown", created: "New inventory", removed: "Inventory removed", previous: "Previous state" },
    age: { days0_29: "0–29 days", days30_59: "30–59 days", days60_89: "60–89 days", days90Plus: "90+ days" },
    integrity: { emptyPeriod: "There is no inventory flow or sales to aggregate in this period.", emptyInventory: "There is no inventory to aggregate.", partial: "Some {area} ledger consistency could not be verified, so affected metrics are hidden.", asOf: "as-of inventory", aging: "inventory age", period: "period inventory flow" },
    metric: { noInventory: "No target inventory", noAmount: "No confirmed amount", costUnavailable: "Purchase cost unavailable", costDetail: "{priced} confirmed · {missing} unknown · {coverage} coverage", turnoverUnavailable: "Turnover cannot be calculated.", turnoverDetail: "Sales {sold} ÷ average daily inventory {average}" },
    asOf: { total: "Total inventory as of {date}", closing: "Closing balance on {date}", sellable: "Sellable", allocated: "Order allocated", restricted: "Sales restricted or under review", longTerm: "Long-term inventory", longTermDescription: "30+ days · excludes order allocations", longTermCost: "Long-term inventory purchase cost", composition: "Inventory status composition as of {date}", compositionDescription: "Classifies every item at the selected close once by its sales, shipment, delivery, or claim meaning.", group: "Status group", included: "Included statuses", quantity: "Quantity", ratio: "Share" },
    aging: { title: "Inventory age and long-term burden", description: "Based on warehouse holding periods at the {date} close; order-allocated inventory is excluded from long-term inventory.", pending: "Inventory age will appear after ledger holding periods are verified.", sku: "SKU / Product", grade: "Grade", target: "As-of target", longTerm: "Long-term", cost: "Confirmed purchase cost", missingPrice: "Price unknown", empty: "There are no long-term inventory SKUs on the as-of date." },
    flow: { turnover: "Sales turnover", sold: "Sales completed", averageInventory: "Average daily warehouse inventory", averageDescription: "Average KST closing quantity by date", newInventory: "New inventory inflow", newDescription: "First inventory creation", customerReturn: "Customer-return reentry", customerReturnDescription: "Warehouse reentry after sale", otherReturn: "Other reentry", otherReturnDescription: "Reentry other than customer returns", exit: "Warehouse exit", exitDescription: "Movement outside the warehouse for delivery, claims, and more", removed: "Inventory removed", removedDescription: "Quantity removed from the ledger", closingChart: "Daily warehouse inventory and sales", closingChartDescription: "Keeps every date in the flow while reducing axis labels for readability.", closing: "Closing warehouse inventory", movementChart: "Daily inventory inflow and outflow", movementChartDescription: "Compares new inflow, reentry, warehouse exit, and removal in the same period.", new: "New inflow", transition: "Inventory status transitions", transitionDescription: "Aggregates status-group transitions by operation during the selected period.", noTransition: "There are no inventory status transitions in this period.", skuTurnover: "Sales turnover by SKU", skuTurnoverDescription: "Compares completed-sale quantity and average daily warehouse inventory for the same SKU.", sku: "SKU / Product", average: "Average inventory", emptySku: "There is no SKU turnover data for this period." },
    scope: { title: "Aggregation basis and reconstruction coverage", description: "Shows the query period, closing basis, and evidence excluded or unverified while reconstructing as-of inventory.", asOf: "As-of inventory", asOfDescription: "{inventory, plural, one {# inventory row} other {# inventory rows}} · {ledger, plural, one {# ledger device} other {# ledger devices}}", cutoff: "Excluded after cutoff", cutoffValue: "{count, plural, one {# row} other {# rows}}", cutoffDescription: "{count, plural, one {# sale excluded} other {# sales excluded}}", price: "As-of price evidence", noneExcluded: "Nothing excluded", excluded: "{count, plural, one {# item excluded} other {# items excluded}}", reconstructionComplete: "Inventory reconstruction verified", reconstructionNeeded: "{count, plural, one {# reconstruction item needs} other {# reconstruction items need}} review" },
    loading: { aggregating: "Aggregating inventory and sales ledgers.", initial: "Loading inventory statistics.", error: "Could not load inventory statistics.", retry: "Try again", refresh: "Refreshing statistics with the same conditions. Current results remain visible." }
  },
  purchase: {
    presentation: { observing: "Observing" },
    coverage: {
      title: "Data basis and reliability", subtitle: "Review price, inspection, and sales-link coverage before interpreting purchase statistics.", terminalInbound: "Terminal inbound batches", terminalDescription: "{purchases, number} purchases · {returns, number} supplier returns", priceCoverage: "Purchase-price coverage", countRatio: "{available, number} / {total, number}", supplierCoverage: "Supplier coverage", supplierDescription: "Out of {total, plural, one {# terminal batch} other {# terminal batches}}", inspectionLinkRate: "Inbound inspection link rate", gradeCoverage: "Purchase-grade coverage", gradeDescription: "{missing, plural, one {# unknown} other {# unknown}}", policyEvidence: "Price-policy evidence", policyDescription: "{modes, number} entry modes · {references, number} reference prices", salesLinkRate: "Original-purchase sales link rate", salesLinkDescription: "Original supplier snapshot {percent, number}%", generatedAt: "Generated at", periodAll: "Entire selected period", warning: "Some statistical data requires review.", success: "No missing links or chronology anomalies require separate review in this range.",
      missingPrice: "{count, plural, one {# confirmed purchase has} other {# confirmed purchases have}} no recorded price", missingSupplier: "{count, plural, one {# terminal batch has} other {# terminal batches have}} no recorded supplier", missingInspection: "{count, plural, one {# terminal batch has} other {# terminal batches have}} no linked inbound inspection", missingGrade: "{count, plural, one {# terminal batch has} other {# terminal batches have}} no known purchase grade", missingPolicy: "{count, plural, one {# confirmed purchase has} other {# confirmed purchases have}} no identifiable price-entry mode", missingInboundSale: "{count, plural, one {# sale has} other {# sales have}} no linked original purchase batch", missingSupplierSnapshot: "{count, plural, one {# sale has} other {# sales have}} no original-supplier snapshot", invalidTimestamp: "{count, plural, one {# record has} other {# records have}} an invalid date", negativeDuration: "{count, plural, one {# record was} other {# records were}} excluded from duration metrics due to invalid chronology"
    },
    summary: { purchaseCount: "Confirmed purchase batches", purchaseBasis: "Based on purchase confirmation", amount: "Purchase amount", averagePrice: "Average purchase price", priceConfirmed: "{count, plural, one {# price confirmed} other {# prices confirmed}}", suppliers: "Suppliers", supplierDescription: "Unique suppliers in terminal batches", supplierReturnRate: "Supplier return rate" },
    monthly: { title: "Monthly purchase outcomes", subtitle: "Confirmed purchases use the confirmation date; supplier returns use the first transition date.", purchase: "Confirmed purchases", supplierReturn: "Supplier returns", inspectionDefect: "Inspection defect outcomes", amountTitle: "Monthly purchase amounts", amountSubtitle: "Missing prices are not included as zero.", month: "Month", count: "Purchases", amount: "Purchase amount", priceConfirmed: "Prices confirmed", priceMissing: "Prices missing", defect: "Inspection defects" },
    product: { title: "Purchase cohort performance by product", subtitle: "Compare confirmed purchases and mature-cohort sales conversion by model, storage, and purchase grade.", model: "Model", storage: "Storage", grade: "Purchase grade", purchase: "Confirmed purchases", amount: "Purchase amount", average: "Average price", supplierReturnRate: "Supplier return rate", defectRate: "Inspection defect rate", conversion30: "30-day sales conversion", conversion60: "60-day sales conversion", conversion90: "90-day sales conversion" },
    supplier: { title: "Supplier performance", subtitle: "Compares supplier returns separately from confirmed customer returns after sale.", supplier: "Supplier", terminal: "Terminal batches", purchase: "Confirmed purchases", amount: "Purchase amount", average: "Average price", supplierReturnRate: "Supplier return rate", defectRate: "Inspection defect rate", customerReturnRate: "Confirmed customer return rate" },
    pricePolicy: { title: "Price-policy outcomes", subtitle: "Compares the stored reference price at confirmation with the actual confirmed price.", mode: "Entry mode", purchase: "Purchases", amount: "Purchase amount", average: "Average price", reference: "Reference coverage", adjustment: "Average adjustment", direction: "Increase / unchanged / decrease", rate: "Reference rate", override: "Reference adjustment", manual: "Manual entry", unknown: "Legacy unknown" },
    inspection: { title: "Inbound inspection quality", subtitle: "Includes only inspections linked to the exact inbound batch.", defectRate: "Inspection defect rate", sample: "Linked inspection sample", sampleDescription: "{count, plural, one {# actual defect} other {# actual defects}}", appearance: "Appearance defect items", appearanceDescription: "A batch may contain multiple defect items.", function: "Functional defect items", functionDescription: "Item share may differ from inspected-device share." },
    leadTime: { title: "Purchase processing time", subtitle: "Uses the median as the primary value and shows P90 and excluded anomalies.", receivedToInspection: "Inbound → Last inspection", inspectionToOutcome: "Last inspection → Terminal state", receivedToOutcome: "Inbound → Terminal state" },
    loading: { initial: "Loading purchase statistics.", aggregating: "Aggregating purchase data.", error: "Could not load purchase statistics.", retry: "Try again", refresh: "Refreshing statistics with the same conditions. Current results remain visible." },
    count: "{count, plural, one {# item} other {# items}}"
  },
  returns: {
    fallback: { loadFailed: "Failed to load return statistics." },
    presentation: { aggregating: "Aggregating", comparisonUnavailable: "Comparison unavailable", comparisonUnavailableDetail: "Both the current and previous mature cohorts are required for comparison.", previousCohort: "Compared with the previous mature cohort" },
    coverage: {
      deviceCount: "{count, plural, one {# device} other {# devices}}",
      claimAfter30: "{count, plural, one {# linked return occurred} other {# linked returns occurred}} more than 30 days after sale", claimBeforeSale: "{count, plural, one {# linked return predates} other {# linked returns predate}} the sale", confirmedInspection: "Confirmed inspection links", costCoverage: "Purchase-cost coverage", eventCount: "{count, plural, one {# query event} other {# query events}}", eventStart: "Event recording started", generatedAt: "Generated at", inspectionDescription: "{count, plural, one {# linked return PG} other {# linked return PGs}}", invalidTime: "{count, plural, one {# item excluded} other {# items excluded}} from duration metrics due to invalid chronology", lastObserved: "Latest return observed", linkDescription: "{detail} · {confirmed, number} confirmed · {unique, number} unique keys", linkRate: "Return-receipt link rate", linkedSales: "Linked sale records", linkedSalesDescription: "{count, plural, one {# cohort sale} other {# cohort sales}}", missingTime: "{count, plural, one {# item has} other {# items have}} a missing or invalid external timestamp", observed: "{returns, number} returns · {cancellations, number} cancellations · {exchanges, number} exchanges", periodAll: "Entire selected period", priceCount: "{available, number} / {total, number}", priceCoverage: "Sale-price coverage", subtitle: "Review collection periods and link, price, and inspection coverage before interpreting return statistics.", success: "No link or chronology anomalies require separate review in this range.", title: "Data basis and reliability", unlinkedReceipt: "{count, plural, one {# return receipt is} other {# return receipts are}} not linked to a sale", unmatchedWithdrawal: "{count, plural, one {# withdrawal is} other {# withdrawals are}} not linked to a sale", warning: "Some statistical data requires review.", ambiguousReceipt: "{count, plural, one {# return receipt has} other {# return receipts have}} duplicate link candidates" },
    summary: { associatedSales: "Sales associated with returns", previous: "Compared with previous cohort", previousDescription: "{detail} · Previous {value}", recovery: "Resellable recovery rate", requestRate: "30-day customer return request rate", vendorFault: "Seller-fault share" },
    overview: { amount: "Associated sales", completed: "Returns completed", connected: "Linked receipts", connectedSales: "Linked sale records", count: "{count, plural, one {# item} other {# items}}", linkedSales: "Linked sales", month: "Receipt month", quantity: "Quantity", quantityValue: "{count, plural, one {# unit} other {# units}}", receipts: "Return receipts", subtitle: "Volume and monthly trend of customer return receipts after sale.", title: "Customer return overview", withdrawn: "Withdrawn", linkRate: "Receipt link rate" },
    cohort: { days14: "14 days", days30: "30 days", days7: "7 days", month: "Sale month", sample: "Cohort sample", sales: "Sales", subtitle: "Shows both the numerator and mature-sale denominator for each period.", title: "Customer return request rate by sales cohort" },
    product: { amount: "Associated sales", delta: "Previous comparison", matureSales: "Mature sales", model: "Model", rate30: "30-day request rate", recovery: "Resale recovery", returnSales: "Return sales", saleGrade: "Grade", sellerFault: "Seller fault", storage: "Storage", subtitle: "Compares return request rates, amounts, fault, and recovery by product combination in the mature cohort.", title: "Returns by product" },
    inspection: { appearanceDefect: "Appearance defect", confirmed: "Confirmed inspections", description: "Only PGs linked to confirmed inspections are included in resale outcomes.", fault: "Fault category", functionDefect: "Functional defect", hold: "Hold", linkedPg: "Linked return PGs", matrixDescription: "Shows only the scope where return reasons can be linked to actual inspection outcomes.", matrixTitle: "Inspection outcomes by reason", nonSellable: "Not sellable", reason: "Return reason", recovery: "Resellable recovery rate", resellable: "Resellable", title: "Return inspection outcomes", unit: "{count, plural, one {# PG} other {# PGs}}", inspectedPg: "Inspected PGs" },
    economics: { associatedCost: "Purchase cost of linked sales", associatedSales: "Sales associated with returns", description: "Includes only linked sale records with known prices; unavailable prices are shown as '-' rather than zero.", nonSellableCost: "Cost of non-sellable or held assets", recoveredCost: "Cost of resellable assets", title: "Amounts associated with returns" },
    leadTime: { description: "Uses the median as the representative value and includes P90, sample size, and excluded anomalies.", observationToApproval: "First observation → Approval request", observationToFinal: "First observation → Local finalization", receiptToObservation: "External receipt → First observation", title: "Processing duration" },
    cancellation: { count: "Cancellation receipts", description: "Shown as a separate population from post-sale customer returns.", month: "Monthly occurrence", products: "Cancelled products", quantity: "Cancelled quantity", reasons: "Cancellation reasons", title: "Pre-shipment cancellations", unit: "{count, plural, one {# unit} other {# units}}" },
    exchange: { description: "Shows exchange receipts, outcomes, and completion time as a separate population.", duration: "Time to terminal state", fault: "Fault category", reasons: "Exchange reasons", receipts: "Exchange receipts", results: "Exchange outcomes", title: "Exchanges" },
    loading: { aggregating: "Aggregating return data.", error: "Could not load return statistics.", initial: "Loading return statistics.", refresh: "Refreshing statistics with the same conditions. Current results remain visible.", retry: "Try again" },
  },
} as const satisfies MessageShape<StatisticsMessages>;
