import type { MessageShape } from "@/quickhack_shared/i18n/message-contract";
import type { SuppliesMessages } from "../ko/supplies.ts";

export const suppliesEn = {
  message: { loading: "Loading supplies data.", loaded: "Supplies data loaded.", loadFailed: "Failed to load supplies data.", actionFailed: "The supplies action failed.", actionComplete: "The supplies action completed.", supplySaved: "The supply information was saved.", movementRecorded: "The supply inventory movement was saved.", consumptionRuleSaved: "The supply consumption rule was saved.", forecastCalculated: "The supply forecast was calculated.", reorderSuggestionsCreated: "Supply reorder suggestions were created.", reorderStatusUpdated: "The supply reorder status was updated.", actionCompleteRefresh: "{message} Refresh to verify the full status.", unsupportedRuleFilters: "The {filters} filters cannot be used with the {trigger} calculation basis." },
  unsaved: { reorderTarget: "Reorder request #{id}", reorderEdit: "Edit reorder request", ruleEdit: "Edit supply-consumption rule", ruleNew: "New supply-consumption rule", selectedSupply: "Selected supply", supplyTarget: "{name} details", supplyNew: "New supply details", movementTarget: "Record quantity for {name}", movement: "Supply quantity record", openSupply: "Open {name}", resetSupply: "Reset to a new supply", switchMovement: "Switch quantity record to {name}", clearMovement: "Clear quantity-record supply", openRule: "Open selected supply-consumption rule", openReorder: "Open reorder request #{id}" },
  actions: { reset: "Reset form", save: "Save", select: "Select" },
  form: { active: "Active supply", baseUnit: "Base unit", category: "Category", code: "Supply code", consumptionPolicy: "Outbound deduction point", defaultSupplier: "Default supplier", editTitle: "Edit supply", inventoryLocation: "Location", lossRate: "Loss rate (%)", maxLeadTime: "Maximum lead time", memo: "Note", minLeadTime: "Minimum lead time", minimumOrderQuantity: "Minimum order quantity", name: "Supply name", newTitle: "Add supply", orderUnit: "Order unit", orderUnitQuantity: "Units per order", reservedQuantity: "Reserved quantity", targetStockDays: "Target stock days", unitCost: "Unit cost" },
  forecast: { actual: "Actual usage", averageDaily: "Daily average", calculate: "Calculate demand forecast", calculation: "Forecast calculation", date: "Calculation date", days: "{elapsed, number} / {lookback, plural, one {# day} other {# days}}", difference: "Difference", elapsed: "Elapsed", empty: "No demand forecast has been calculated.", errorRate: "Error rate", lookback: "Lookback period", predicted: "Predicted usage", recommended: "Recommended purchase", reorderPoint: "Reorder point", result: "Demand forecast", safetyStock: "Safety stock", stockout: "Expected stockout", targetStock: "Target stock", validation: "Forecast validation", validationEmpty: "No demand forecast is available for validation.", validationHint: "Actual consumption accumulated after the calculation date is compared with predicted usage. A forecast calculated today requires at least one day before validation.", validationPeriod: "Validation period", validationStatus: "Result" },
  validationState: { PENDING: "Pending validation", NO_USAGE: "No usage", GOOD: "Good", WARNING: "Warning", HIGH_ERROR: "High error" },
  trigger: { PURCHASED_DEVICE: "Purchased device", SHIPMENT_CREATED: "Shipment or tracking item", ORDER_ITEM: "Order item quantity", PACKING_COMPLETED: "Inventory-audit packing completed", RETURN_RECEIVED: "Return received" },
  inventory: { active: "Active", empty: "No supplies registered.", inactive: "Inactive", title: "Supply inventory" },
  movement: { empty: "No recent quantity history.", formTitle: "Record quantity", save: "Save quantity record", selectSupply: "Select a supply", title: "Recent quantity history", type: { adjustment: "Adjustment", consumed: "Consumed", discarded: "Discarded", inbound: "Inbound", returned: "Returned" } },
  policy: { confirmedOnly: "Deduct only after packing confirmation", prepackAllowed: "Deduct on prepack or packing confirmation" },
  reorder: { action: "Action", createSuggestions: "Create suggestions", editTitle: "Update reorder status", empty: "No reorder requests.", expectedUnitCost: "Expected unit cost", forecastOutdated: "Forecast refresh required", historyMore: "Show completed history", latestRecommended: "Latest recommendation: {quantity}", listTitle: "Reorder requests", loading: "Loading", ordered: "Ordered", orderedQuantity: "Ordered quantity", reason: "Reason / note", received: "Received", receivedQuantity: "Received quantity", recommended: "Recommended", recommendedTargets: "Recommended purchase targets", request: "Requested", requestId: "Reorder request", requestedQuantity: "Requested quantity", save: "Save status", saveHint: "Saving Received with a received quantity automatically increases supply inventory.", select: "Select", status: "Status", statusValue: { approved: "Approved", cancelled: "Cancelled", ordered: "Ordered", received: "Received", requested: "Purchase requested", suggested: "System suggestion" }, supplier: "Supplier" },
  rule: { active: "Active", allItems: "This calculation basis aggregates every item without an additional product filter.", calculationBasis: "Calculation basis", filterField: { channel: "Channel", inventoryStatus: "Inventory status", model: "Model", saleGrade: "Sale grade", warranty: "Warranty" }, filterForm: { channel: "Channel filter", inventoryStatus: "Inventory-status filter", model: "Model filter", saleGrade: "Sale-grade filter", warranty: "Warranty filter" }, editTitle: "Edit demand rule", empty: "No demand rules registered.", filter: "Filter", memo: "Note", newTitle: "Add demand rule", quantity: "Demand", quantityPerUnit: "Quantity per event", registered: "Registered demand rules", save: "Save rule", selectSupply: "Select a supply", status: "Status", tab: "Demand rules", trigger: "Basis", inactive: "Inactive", edit: "Edit" },
  tabs: { forecast: "Forecast results", rules: "Demand rules", validation: "Forecast validation" },
  summary: { active: "Active supplies", belowReorder: "Below reorder point", openReorders: "Open reorders", registered: "Registered supplies" },
  table: { action: "Action", after: "After", available: "Available", before: "Before", category: "Category", code: "Code", current: "Current", date: "Date", location: "Location", name: "Supply name", operator: "Operator", policy: "Outbound deduction point", quantity: "Quantity", reason: "Reason", reserved: "Reserved", status: "Status", supply: "Supply", type: "Type" },
} as const satisfies MessageShape<SuppliesMessages>;
